### ISSUE TITLE
v1.16b not available on flathub

### ISSUE THREAD

**Issue by MandavkarPranjal** [zen-browser/desktop#10528]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

can't update zen from flathub

### Expected behavior

when run "flatpak update app.zen_browser.zen" it should update to latest version

### Actual behavior

it shows there are no updates available

### Steps to reproduce

run "flatpak update app.zen_browser.zen" with zen v.1.15.5b installed

### Screenshots and videos

<img width="1916" height="1052" alt="Image" src="https://github.com/user-attachments/assets/c0920bba-5f9c-47eb-a27d-1364c0f5745e" />

### Version

v.1.15.5b

### What platform are you seeing the problem on?

Linux (Flatpak)

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

**Comment by Samuel85-git** [comment]
I have the same problem, there are still no updates on the flatpak version

**Comment by ClairDePrince** [comment]
I think it was caused by https://github.com/flathub/app.zen_browser.zen/issues/106, and resolved with https://github.com/zen-browser/desktop/pull/10510. The next release/build should be available on Flathub.

**Comment by MandavkarPranjal** [comment]
So next bug fix version will available on flathub, but not current latest

**Comment by ClairDePrince** [comment]
> So next bug fix version will available on flathub, but not current latest

That's what I understood

**Comment by mr-cheffy** [comment]
It will be released today, sorry for the delay.

**Comment by luke-court** [comment]
Just so you know the latest version still doesn't appear to be up on flathub at the minute

**Comment by ClairDePrince** [comment]
> Just so you know the latest version still doesn't appear to be up on flathub at the minute

For me it showed up as an update (1.16.1b), did you make sure to refresh?

**Comment by luke-court** [comment]
I just got the update now
