### ISSUE TITLE
Bookmarks got multiplied in toolbar when opening a new window

### ISSUE THREAD

**Issue by JesterC6527** [zen-browser/desktop#11434]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

as title, the old problem returns.

### Expected behavior

same bookmark bar as the first window

### Actual behavior

bookmarks got multiplied in toolbar when opening a new window

### Steps to reproduce

1. open a window
2. open a new window

### Version

1.17.9b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Bookmarks

### Relevant log output if applicable

```shell

```

**Comment by JesterC6527** [comment]
solved in 1.17.10b but sometimes makes compact mode toolbar perform weirdly.

**Comment by Titaniumtown** [comment]
I can reproduce on version 1.18t. I'm on NixOS

**Comment by JesterC6527** [comment]
this problem happens again.
the version is 1.17.15b (Firefox 146.0.1)

**Comment by brazenvoid** [comment]
Not fixed 

<img width="1484" height="167" alt="Image" src="https://github.com/user-attachments/assets/5c8fd999-ed0a-4f40-9e3b-8404ba55f7c2" />
