### ISSUE TITLE
Youtube crashes Zen

### ISSUE THREAD

**Issue by King-Benx** [zen-browser/desktop#11610]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Currently on mac Zen 1.17.14b (Firefox 146.0) (aarch64), opening youtube crashes the browser

### Expected behavior

Should not crash the browser

### Actual behavior

Zen crashes the browser completely

### Steps to reproduce

Launch Youtube

### Version

1.17.14b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

[zen-2025-12-10-164011.txt](https://github.com/user-attachments/files/24163964/zen-2025-12-10-164011.txt)
[zen-2025-12-11-124042.txt](https://github.com/user-attachments/files/24163965/zen-2025-12-11-124042.txt)
[zen-2025-12-14-101601.txt](https://github.com/user-attachments/files/24163966/zen-2025-12-14-101601.txt)

[zen-2025-12-14-195648.txt](https://github.com/user-attachments/files/24180905/zen-2025-12-14-195648.txt)

**Comment by Propheticus** [comment]
Any details / logs from the macOS crash reporter? 
and/or anything in `about:crashes` (open as URL) in Zen?

Or `$HOME/Library/Application Support/Zen/Crash Reports/Pending`

**Comment by King-Benx** [comment]
@Propheticus 
[zen-2025-12-10-164011.txt](https://github.com/user-attachments/files/24163943/zen-2025-12-10-164011.txt)
[zen-2025-12-11-124042.txt](https://github.com/user-attachments/files/24163945/zen-2025-12-11-124042.txt)
[zen-2025-12-14-101601.txt](https://github.com/user-attachments/files/24163944/zen-2025-12-14-101601.txt)

**Comment by Propheticus** [comment]
The most recent of those states it's on version 1.17.13b
A mac specific issue was solved in 1.17.14b. Do you have this new one already?
(I know the issue report says 1.17.14b. Double checking to make sure we're not chasing our tails)

**Comment by WangRyan408** [comment]
Getting the same issue on Linux, clicking on any youtube video crashes.
Getting the following output when running directly through kitty:
```
Exiting due to channel error.
fish: Job 1, 'zen-browser' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Propheticus** [comment]
@WangRyan408 that could be a case of #11562 
Related to Mesa drivers. See my earlier comment https://github.com/zen-browser/desktop/issues/11618#issuecomment-3655667035

**Comment by WangRyan408** [comment]
> [@WangRyan408](https://github.com/WangRyan408) that could be a case of [#11562](https://github.com/zen-browser/desktop/issues/11562) Related to Mesa drivers. See my earlier comment [#11618 (comment)](https://github.com/zen-browser/desktop/issues/11618#issuecomment-3655667035)

Just downgraded Mesa to 25.2.7, issue is still here :C

Getting slightly different output:
```
[Child 5150, MediaDecoderStateMachine #1] WARNING: Decoder=7f298448ac00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005): file /home/ubuntu/actions-runner/_work/desktop/desktop/engine/dom/media/MediaDecoderStateMachineBase.cpp:168
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=62.5437) Exiting due to channel error.
fish: Job 1, 'zen-browser' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Propheticus** [comment]
@WangRyan408 Make sure you have FFMpeg version 7 or lower installed. Most importantly the libavcodec.

**Comment by WangRyan408** [comment]
> [@WangRyan408](https://github.com/WangRyan408) Make sure you have FFMpeg version 7 or lower installed. Most importantly the libavcodec.

I think I'll just go back to FF for the time being, I'd rather not downgrade FFmpeg and all of its deps too much of a hassle. Hopefully this gets fixed soon.

**Comment by King-Benx** [comment]
@Propheticus  1.17.14b
[zen-2025-12-14-195648.txt](https://github.com/user-attachments/files/24180917/zen-2025-12-14-195648.txt)

**Comment by Propheticus** [comment]
> I think I'll just go back to FF for the time being, I'd rather not downgrade FFmpeg and all of its deps too much of a hassle. Hopefully this gets fixed 

Firefox installed via the same type of installer (flatpak, tarball, aur package) does not have the same issue? The ffmpeg dependency is also there for Firefox.
You dont have to downgrade btw, you can install for instance ffmpeg4.4 (or latest version of 6 or 7) alongside ffmpeg8

**Comment by Propheticus** [comment]
> [@Propheticus](https://github.com/Propheticus) 1.17.14b [zen-2025-12-14-195648.txt](https://github.com/user-attachments/files/24180917/zen-2025-12-14-195648.txt)

Have you tried without extensions (or menu > help > troubleshoot mode)?

**Comment by WangRyan408** [comment]
Ok I don't know what happened but zen isn't crashing anymore?

EDIT: nvm still crashing, its crashing randomly and I don't know the exact pattern but yeah gonna stick with FF until this gets fixed.

**Comment by AdamBearWA** [comment]
Happening in Windows too now running v1.17.15b

**Comment by ksweetie** [comment]
This is happening to me consistently on MacOS. I updated from 1.18.1b to 1.18.3b last night. I never had a crash before 1.18.3b, but now it's happening consistently within 1-30 seconds of a YouTube video.

I tried troubleshoot mode and it still crashed.

Firefox still works fine.

Edit: I downgraded to 1.18.1b and it's still immediately crashing on any YouTube video. But I'm positive with the timing coinciding with updating last night at 8:30 and then the crashes starting right after it. And I had never seen a crash before this. I've been using Zen for about a year.

**Comment by NhanHoThanh** [comment]
I'm still suffering from this bug, after Zen auto update to the newest version (1.17.14b)

**Comment by mr-cheffy** [comment]
that's not the newest version

**Comment by AdamBearWA** [comment]
I'm on `1.18.7b` and it's still happening for me on Windows.

**Comment by mr-cheffy** [comment]
Maybe try clearing cache

**Comment by GregoryBai** [comment]
Re-installed and looks like it solved the issue (arch)

Edit: Nope, crashed right after the comment
