### ISSUE TITLE
None of the Zen mods are working

### ISSUE THREAD

**Issue by Aaditya630** [zen-browser/desktop#2523]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am not able to use any of the Zen mods

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Its not working
```

**Comment by RayZ3R0** [comment]
Can you give more info please, which mods are you trying to use?

**Comment by jobsrobson** [comment]
I'm also having trouble installing Mods. On the store page, when I click to install, the button turns gray, but nothing happens after that. The issue started with version 1.0.1-a.16. I've uninstalled the latest version (including all my profiles) and installed an older version of Zen (a.13). The problem occurred in that older version as well.

![image](https://github.com/user-attachments/assets/edba23b1-5b9f-45af-a73c-58d3d85d87dd)

**Comment by RayZ3R0** [comment]
This can be temporarily fixed by 

Open Profile Folder -> chrome -> move or delete both zen-themes.css and zen-themes folder

but yeah this is an issue, will move this up for fixing

**Comment by jobsrobson** [comment]
I've tried the workaround, but it didn’t work either. I've also noticed that Zen isn’t able to check for updates (Help > About Zen). It keeps loading for a while and then shows an error message. Could this be related to the issue with installing Mods?

**Comment by RayZ3R0** [comment]
Does this happen on a new profile?

**Comment by jobsrobson** [comment]
Yes, it also happens with a new profile. I'm using Windows 11 (23H2 Beta, 22635.4440) and Zen a.17. The issue persists even after a clean reinstallation (using Revo Uninstaller). There are no active extensions and I'm not using Firefox account sync.

**Comment by Vistaus** [comment]
I also have an issue with installing mods. I installed Zen Browser last night, so it's a clean install. But when I go to the Zen Mods page, it prompts me to download Zen instead of offering me to install the mods I click on. So it seems to not be recognizing Zen.

**Comment by jobsrobson** [comment]
Update: It seems that the problem is related to an incompatibility between my home internet network and the Zen Mods store. I ran tests on different PCs connected to the same Wi-Fi, and the issue with installing Zen Mods or updating Zen also occurs on these devices. However, when connected to a different network (such as my work network), the Zen Mods installation works fine, and the update search returns no errors.

**Comment by simulatedecosystems** [comment]
> This can be temporarily fixed by
> 
> Open Profile Folder -> chrome -> move or delete both zen-themes.css and zen-themes folder

This doesn't work here, latest Max OS X and Zen browser version 1.0.1-a.19, have struggled consistently with Zen Mods installing fine, but not doing anything for a good while now. Seems to persist even with a new profile.
