### ISSUE TITLE
[Flatpak] Failed to create shader cache (Permission denied)

### ISSUE THREAD

**Issue by litemotiv** [zen-browser/desktop#2767]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The linux flatpak version of Zen is trying to create shader cache but fails with a permission denied error. The issue is most easily reproduced on a site like youtube.com, by clicking around. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 09 16:23:42 fedora io.github.zen_browser.zen.desktop[339532]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
[...]
```

**Comment by LeMoonStar** [comment]
I can reproduce this by viewing the output of `journal -f` and clicking on a video on the YouTube main page:
```
Nov 09 16:40:44 aaron-acralis-fedora io.github.zen_browser.zen.desktop[9855]: Failed to create /home/aaron/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
Nov 09 16:40:44 aaron-acralis-fedora io.github.zen_browser.zen.desktop[9855]: Failed to create /home/aaron/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
Nov 09 16:40:44 aaron-acralis-fedora io.github.zen_browser.zen.desktop[9855]: Failed to create /home/aaron/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
Nov 09 16:40:44 aaron-acralis-fedora io.github.zen_browser.zen.desktop[9855]: Failed to create /home/aaron/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
```

The directory that zen is trying to create already exists:
```
$ ls -la /home/aaron/.var/app/io.github.zen_browser.zen/cache                                                                                        Sat 09 Nov 2024 16:54:34 CET
total 0
drwxr-xr-x 1 aaron aaron 106 Sep 17 19:59 ./
drwxr-xr-x 1 aaron aaron  62 Aug 23 17:44 ../
drwxr-xr-x 1 aaron aaron 810 Aug 23 17:44 fontconfig/
drwx------ 1 aaron aaron   0 Sep 17 19:59 mesa_shader_cache/
drwx------ 1 aaron aaron 602 Sep 10 22:29 mesa_shader_cache_db/
drwxr-xr-x 1 aaron aaron  50 Nov  9 16:16 tmp/
drwx------ 1 aaron aaron  96 Aug 23 17:44 zen
```

**Comment by memchr** [comment]
Could be a bug in the upstream related hardware video decoding. You may be able to reproduce this in Firefox too by setting `media.ffmpeg.vaapi.enabled` to true, which this browser seems to do by default on Linux. Then play a random video and watch the log output.

The error itself comes from [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/blob/dc1fe83aa524f3297905d33841ca2420f84d8b93/src/util/disk_cache_os.c#L135), but in this case it is an EACCES instead of an EEXIST, which is curious.

**Comment by litemotiv** [comment]
> Could be a bug in the upstream related hardware video decoding. You may be able to reproduce this in Firefox too by setting `media.ffmpeg.vaapi.enabled` to true, which this browser seems to do by default on Linux. Then play a random video and watch the log output.
> 

I have vaapi enabled in both stock Firefox (non-flatpak) and Zen (flatpak), the shader errors only appear in Zen. 

The hardware decoding itself seems to work okay on both browsers. As far as i can tell the shader cache is used to make consequent renderings faster by caching rendered data to disk. 

Below are logs for both Firefox and Zen where i start each browser, open Youtube.com and scroll down one page. 

**Firefox**

```
nov 10 17:55:24 fedora org.mozilla.firefox.desktop[214283]: libva info: VA-API version 1.22.0
nov 10 17:55:24 fedora org.mozilla.firefox.desktop[214283]: libva info: Trying to open /usr/lib64/dri-nonfree/radeonsi_drv_video.so
nov 10 17:55:24 fedora org.mozilla.firefox.desktop[214283]: libva info: Trying to open /usr/lib64/dri-freeworld/radeonsi_drv_video.so
nov 10 17:55:24 fedora org.mozilla.firefox.desktop[214283]: libva info: Found init function __vaDriverInit_1_22
nov 10 17:55:25 fedora org.mozilla.firefox.desktop[214283]: libva info: va_openDriver() returns 0
nov 10 17:55:25 fedora rtkit-daemon[980]: Successfully made thread 214360 of process 213259 (/usr/lib64/firefox/firefox) owned by '1000' RT at priority 10.
```

**Zen**
```
nov 10 17:56:48 fedora systemd[2069]: Started app-gnome-io.github.zen_browser.zen-215200.scope - Application launched by gnome-shell.
nov 10 17:56:48 fedora systemd[2069]: Started app-flatpak-io.github.zen_browser.zen-215200.scope.
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: VA-API version 1.19.0
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: Found init function __vaDriverInit_1_19
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:00 fedora io.github.zen_browser.zen.desktop[215602]: libva info: va_openDriver() returns 0
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
nov 10 17:57:15 fedora io.github.zen_browser.zen.desktop[215602]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
[...]
``` 

I wonder if the error on Zen could be related to the missing line about process ownership that is visible for stock Firefox.

**Comment by LeMoonStar** [comment]
I can confirm this is also **not** happening on Firefox when installed via the Flatpak with `media.ffmpeg.vaapi.enabled` enabled.

**Comment by memchr** [comment]
I can reproduce it with firefox on archlinux, but not on fedora.

I think this is related to how file system brokering is [configured](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/2e1d2f3a9b21c8ae05ea898544d4a6196fadfd60/PKGBUILD#L112), as firefox's sandbox traps mkdir calls, which might explain why mkdir returned EACCES instead of EEXIST.
```c
[656] Sandbox: SandboxBroker: denied op=stat rflags=0 perms=0 path=/home/user/.cache for pid=995
[995] Sandbox: Failed errno -13 op stat flags 00 path /home/user/.cache
[656] Sandbox: SandboxBroker: denied op=mkdir rflags=700 perms=0 path=/home/user/.cache for pid=995
[995] Sandbox: Failed errno -13 op mkdir flags 0700 path /home/user/.cache
Failed to create /home/user/.cache for shader cache (Permission denied)---disabling.
```

**Comment by litemotiv** [comment]
Interesting to note is that when manually removing the two shader cache directories:

```
~/.var/app/io.github.zen_browser.zen/cache/mesa_shader_cache
~/.var/app/io.github.zen_browser.zen/cache/mesa_shader_cache_db
```

they will be automatically recreated on the next launch and populated with some index files. So the basic fs permission for Zen to create the directories and files is there. 

After that the browser will give back the same error about permissions when trying to create the actual shade cache files.

```
nov 11 18:10:18 fedora io.github.zen_browser.zen.desktop[311842]: Failed to create /home/litemotiv/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
```

**Comment by litemotiv** [comment]
The issue can be fixed by manually providing the shader cache location as an environment variable. Launching Zen as below will remove the errors:

```
$ flatpak run --env=MESA_SHADER_CACHE_DIR=$HOME/.var/app/io.github.zen_browser.zen/cache/mesa_shader_cache_db io.github.zen_browser.zen
```

**Comment by codenamek83** [comment]
Hi @litemotiv

I am also encountering this issue. Upon its initial run, Zen creates both the mesa_shader_cache and mesa_shader_cache_db directories with 700 permissions, meaning only the owner has access to these directories. This, I believe, restricts Zen or another process from writing or creating files in the directory. However, Zen is able to recreate these folders if we manually delete them. In my case, I changed the permissions to 755, and the issue is resolved. Would it be possible to revisit the issue and update the Flatpak manifest if necessary? I would be glad to assist if you need any further information.

**Comment by litemotiv** [comment]
Hi @codenamek83 

It's interesting that 755 permissions have an effect on your setup, since that adds read permissions to G+O while the error pertained to write permissions:

```
Failed to create /home/<user>/.var/app/io.github.zen_browser.zen/cache for shader cache (Permission denied)---disabling.
```

In my local tests i set the permissions to 777 and even then the error persisted, so this wasn't a working solution on my system. (Relaxing the write permissions would be a security hazard so this would not be a permanent solution)

Can you see if the `MESA_SHADER_CACHE_DIR` environment variable was set correctly on your system and if it points to the directory that corresponds to your Zen config/cache?

**Comment by codenamek83** [comment]
Hi @litemotiv

I checked for the environment variable using the following commands on both my primary device (Ubuntu) and a virtual machine (Linux Lite), but the variable doesn’t seem to exist. 

```
flatpak run --env=MESA_SHADER_CACHE_DIR env io.github.zen_browser.zen
flatpak run --command=bash io.github.zen_browser.zen
```

**Comment by litemotiv** [comment]
@codenamek83 

The startup ENV variables of the flatpak are visible in the file below:

https://github.com/zen-browser/desktop/blob/dev/flatpak/io.github.zen_browser.zen.yml.template

The variable we added in this ticket to fix the shader cache issue is the following:

```
--env=MESA_SHADER_CACHE_DIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID/cache/mesa_shader_cache_db 
```

If everything is well that should be enabled on your system, otherwise you will get the Permission Denied error. If the variable is not active on your system, that might be a specific issue to look into.

**Comment by codenamek83** [comment]
Hi @litemotiv 

Initially, I thought it was just my primary device that didn't have this variable, so I installed Zen on a virtual machine to test it. Since it was a different distro and DE, I expected different results, but the variable was still missing.

**Comment by litemotiv** [comment]
@codenamek83 

Right, that could indicate a problem in that case. Do you see the other ENV variable that is set?

```
--env=GTK_PATH=/app/lib/gtkmodules
```

If you do, then the shader cache ENV variable specifically is failing, and we would have to look into why that is. Maybe it could have to do with the local variables in the string that would need to be placed between accolades, but i'm not sure.

It would then become:
```
--env=MESA_SHADER_CACHE_DIR=${{XDG_RUNTIME_DIR}}/app/${{FLATPAK_ID}}/cache/mesa_shader_cache_db 
```

**Comment by codenamek83** [comment]
@litemotiv 

Below is the output of the env command.

ALSA_CONFIG_DIR=/usr/share/alsa
ALSA_CONFIG_PATH=/usr/share/alsa/alsa-flatpak.conf
AT_SPI_BUS_ADDRESS=unix:path=/run/flatpak/at-spi-bus
CLUTTER_IM_MODULE=ibus
COLORTERM=truecolor
container=flatpak
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/flatpak/bus
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
DEFAULTS_PATH=/usr/share/gconf/xfce.default.path
DESKTOP_SESSION=xfce
DISPLAY=:99.0
__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS=/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d
FLATPAK_ID=io.github.zen_browser.zen
FLATPAK_SANDBOX_DIR=/home/adm-john/.var/app/io.github.zen_browser.zen/sandbox
GDM_LANG=en_US
GDMSESSION=xfce
GI_TYPELIB_PATH=/app/lib/girepository-1.0
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
GTK3_MODULES=xapp-gtk3-module
GTK_IM_MODULE=ibus
GTK_MODULES=:canberra-gtk-module:gail:atk-bridge
GTK_PATH=/app/lib/gtkmodules
HOME=/home/adm-john
LANG=en_SG.UTF-8
LANGUAGE=en_SG:en
LD_LIBRARY_PATH=
LOGNAME=adm-john
MANDATORY_PATH=/usr/share/gconf/xfce.mandatory.path
PANEL_GDK_CORE_DEVICE_EVENTS=0
PATH=/app/bin:/usr/bin
PS1=[📦 $FLATPAK_ID \W]\$ 
PULSE_CLIENTCONFIG=/run/flatpak/pulse/config
PULSE_SERVER=unix:/run/flatpak/pulse/native
PWD=/home/adm-john
PYTHONUSERBASE=/var/data/python
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=qt5ct
SESSION_MANAGER=local/APP-DMZ:@/tmp/.ICE-unix/2057,unix/APP-DMZ:/tmp/.ICE-unix/2057
SHELL=/bin/sh
SHLVL=3
SSH_AGENT_PID=2265
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXEumEaF/agent.2260
TERM=xterm-256color
USER=adm-john
_=/usr/bin/env
VTE_VERSION=6800
WINDOWID=39845891
XAUTHORITY=/run/flatpak/Xauthority
XDG_CACHE_HOME=/home/adm-john/.var/app/io.github.zen_browser.zen/cache
XDG_CONFIG_DIRS=/app/etc/xdg:/etc/xdg
XDG_CONFIG_HOME=/home/adm-john/.var/app/io.github.zen_browser.zen/config
XDG_CURRENT_DESKTOP=XFCE
XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
XDG_DATA_HOME=/home/adm-john/.var/app/io.github.zen_browser.zen/data
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/adm-john
XDG_MENU_PREFIX=xfce-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=xfce
XDG_SESSION_ID=c1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7
XMODIFIERS=@im=ibus

**Comment by litemotiv** [comment]
@codenamek83 

I'm not sure why the shader cache variable isn't applied on your system. You could perhaps as a test start Zen from a terminal with the variable set manually to see if that works. 

Since `XDG_CACHE_HOME` is listed on your system the following would likely suffice:

```
$ flatpak run --env=MESA_SHADER_CACHE_DIR=$XDG_CACHE_HOME/mesa_shader_cache_db io.github.zen_browser.zen
```

We'd have to find out why the variable doesn't work from the flatpak YML file.

**Comment by codenamek83** [comment]
@litemotiv 

Is this the correct way to parse the env variable? I received 'command not found' when I tried this.

`flatpak run --env=MESA_SHADER_CACHE_DIR=$XDG_CACHE_HOME/mesa_shader_cache_db io.github.zen_browser.zen`

I tried this format and was able to start the app. However, the result was the same, the variable was still not set.

`flatpak run --env=MESA_SHADER_CACHE_DIR/mesa_shader_cache_db io.github.zen_browser.zen`

**Comment by litemotiv** [comment]
@codenamek83 

> Is this the correct way to parse the env variable? I received 'command not found' when I tried this.
> 
> `flatpak run --env=MESA_SHADER_CACHE_DIR=$XDG_CACHE_HOME/mesa_shader_cache_db io.github.zen_browser.zen`

Yes that would be the right way, i just copy pasted that line and see no errors on my system. 

When launching Zen that way i get no 'shader cache permission denied errors', the permissions of the directory are set to 700.
