### ISSUE TITLE
Essentials & Pinned Disappear With Second Window

### ISSUE THREAD

**Issue by justingallant1988** [zen-browser/desktop#4126]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Essentials and pinned tabs are disappearing only when multiple windows are being utilized. If you quit both browser windows at the same time OR quit the second window last, essentials and pinned tabs will be lost from some of the workspaces but not always all. They will not be lost if you close the second window first. Reproducible every time. Video previously attached   on Discord

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Buckeyes23** [comment]
This happens on Windows also. I have multiple monitors and if I close and reopen , I lose all my tabs

**Comment by kgarrett67** [comment]
This started happening to me yesterday on OpenSUSE Leap 15.5, but had been working fine before although the version hasn't changed.

I'm using version 1.0.2-b.5.

Also, while this is happening, the bookmarks in the Bookmark Bar will duplicate at random.

**Comment by luke-monroe** [comment]
I think this was fixed in Version 1.7.1b
I had it before (Windows 11) but it seems to be fine now. I think it was mentioned in release notes too
@kgarrett67 

Edit: it was reported below that this is still a bug.

**Comment by miles202** [comment]
I lost all Essentials and pinned tabs on 1.7.1b (Mac) this morning.

**Comment by aries1232** [comment]
I lost essentials on 1.7.1b (windows) when open multiple windows

**Comment by YouCanTouCan** [comment]
I could not replicate this reliably on Windows 10, 1.8.2b. Is this still a problem people are having?

**Comment by blakegearin** [comment]
I'm still having this issue on macOS Sonoma `14.6.1` running `1.10.1b1`

**Comment by mr-cheffy** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Essentials%20%26%20Pinned%20Disappear%20With%20Second%20Window%0A
