### ISSUE TITLE
Right click menu font color is dark regardless of dark theme 

### ISSUE THREAD

**Issue by thairanaru** [zen-browser/desktop#42]
If you right click something, the font color of the menu appears dark even if you have Zen Dark or Zen Galaxy enabled. 

![image](https://github.com/user-attachments/assets/ffff1fd3-574b-4969-b353-d9907c656aaf)

**System information:**
Arch Linux, niri
Zen Browser Version 1.0.0-a.1 (64-bit)

**Comment by mauro-balades** [comment]
![Screenshot_20240712_195851](https://github.com/user-attachments/assets/8b0b893f-34c4-480a-8d3d-af87f4fd8dd5)

have you tried to restart the browser? Maybe changing themes messed it up a bit

**Comment by quissberry** [comment]
I restarted it but the problem persists. However, when I switch to GNOME, the problem clears away. So it might be Niri or WM specific issue. 
To clarify, everything else looks fine.

**Comment by mauro-balades** [comment]
ill look into it, thanks a lot!

**Comment by mauro-balades** [comment]
it has been fixed in (https://github.com/zen-browser/desktop/commit/69e352624eb77d6b9058dad145f1f5a3054a41dc), it will be visible on the next release!

**Comment by bhupeshpr25** [comment]
I'm still seeing this problem in Pop OS 22.04 Linux

**Comment by rdbo** [comment]
I'm also seeing this issue using the Flatpak version (1.0.1-a.19) on Alpine Linux
![image](https://github.com/user-attachments/assets/833bb3eb-468d-4d89-bbbb-f7f782bda78a)

**Comment by willstocks** [comment]
Definitely still an issue for me- Arch 6.13.4, Zen 1.8.2b, using the default "Dark" theme

**Comment by siradaninsan** [comment]
I'm having the same issue on fedora 41 hyprland

**Comment by jlodenius** [comment]
same issue on Arch 6.14.1, the only solution I've found is to set `widget.gtk.native-context-menus` to `true` in `about:config` you won't get the same looking menu, nor dark mode but atleast it will be readable
