### ISSUE TITLE
[TWILIGHT] New update has some bugs I've found so far

### ISSUE THREAD

**Issue by 12th-devs** [zen-browser/desktop#4304]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When first updating Twilight and upon reopening the browser all of my pinned tabs and regular tabs were deleted but not my essentials (I love the new backgrounds ❤️) This has happened to me twice, and seems to be an issue with me but, to my understanding, Zen is taking a long time to boot up and I have no visual indicator, so I try and open it again. But I am greeted with a popup saying Zen is running but not responding (the same form you get if you try to run Twilight and Stable at the same time). If you need more info or for me to reproduce just let me know. My second issue is when I tried to pin 4 tabs in my 3rd workspace for school and then went back to my personal workspace, all of the pinned tabs had moved to that workspace, I just had to pin them again and everything was fine.

(No I do not have shared workspace pins, or whatever the setting name is)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7t

### What platform are you seeing the problem on?

Windows

### Data from about:support if applicable (click on the "Copy text to clipboard" button)

<details>
  <summary>about:support</summary>
  

  ```
Not Relavent
  ```
</details>

**Comment by thibaultmol** [comment]
I'm running into the same problem. It's bad enough that i'm considering rolling back to the previous version honestly... I can't work like this...
it's interesting. I had multiple windows open in my last session before I switched to 6b.
The main window didn't have them, but all my other windows did. BUT the moment I switch workspace, they also start disappearing on the other windows
![image](https://github.com/user-attachments/assets/1930de9e-055c-47cc-9150-33e8459420f0)


![image](https://github.com/user-attachments/assets/7f1a663d-6579-44c9-91f5-cbcc5d5a752b)

(this is not how I use Zen obv, just put the windows like this for the screenshot xd)

**Comment by mr-cheffy** [comment]
Could you send a video?

**Comment by thibaultmol** [comment]
I restart zen using about:profiles restart. and now the opposite happened. essentials appeared in the main window but not in the others.

also one important thing to mention: it seems like all essential and pinned tabs load in the essentials ui. I don't have that many essentials. but it seems like the pinned tabs also end up in that part of the ui somehow

[av1.webm](https://github.com/user-attachments/assets/d85f3d43-e3a4-4773-a9b1-d87188ad1a4c)

**Comment by thibaultmol** [comment]
I tried disabling all addons and restarting. but still the same problem.

(recording isn't of that repro run. But the same thing happens with all addons off) 
[Screencast_20250112_210746.webm](https://github.com/user-attachments/assets/756c2629-1f88-4b94-aac0-1d07d980bac3)

1.6b (Firefox 134.0) (64-bit) installed using  https://github.com/youwen5/zen-browser-flake/

Operating System: NixOS 25.05
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.6.69 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
Memory: 60.6 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: Framework
Product Name: Laptop 13 (AMD Ryzen 7040Series)
System Version: A7

EDIT: oh I just realized that essentials are just fully. those are all the pinned tabs from all the workspaces in one, that then dissapear when you switch workspace

**Comment by thibaultmol** [comment]
Did some more testing:
- seems like essentials are just gone? I tried setting a tab as an essential. and that works as expected now. So it seems like the update somehow made me lose my essentials
- pinned tabs: I still have the problem where all pinned tabs from all workspaces appear in one go even after I set a tab as a pinned tab (which might cause a rewrite of whatever file or somehting) but that has no effect

**Comment by mr-cheffy** [comment]
[Screencast from 2025-01-12 21-53-05.webm](https://github.com/user-attachments/assets/062e1524-e6e3-4a21-8ba0-e93f934bad72)

it does work for me...

also, these are **not** essentials:
![image](https://github.com/user-attachments/assets/1860b8be-5f3a-408f-b069-df6a3053a6e8)

**Comment by thibaultmol** [comment]
Sorry I corrected in my last comment that my essentials are gone and All the pinned tabs from each of my workspaces all show up at once.

I think it's specifically something from going to the previous version to 1.6 b. As that's exactly when It started happening.

I'm not sure what more info I can provide to help reproduce it

**Comment by 12th-devs** [comment]
Also been unable to reproduce again... 😅

**Comment by mr-cheffy** [comment]
Could you also send a video?

**Comment by 12th-devs** [comment]
of?  I don't know what happened but I do not think it was just Zen's fault... I need to do a fresh install of Windows but I am putting it off

Edit: @thibaultmol and I also had different bug. My essentials were still present but all of my pinned tabs and regular tabs were deleted.

**Comment by azhe403** [comment]
Search engine settings breaking after update to 1.7. Add new search engine can't too.
when create new profile work fine
![image](https://github.com/user-attachments/assets/fd1277be-5d87-4d90-b472-b93f3ebf06af)

**Comment by chrisgeo** [comment]
I think I found out what might be the cause of the disappearing settings.

@thibaultmol do you have another profile that has "default" in the name after this?

Basically, I had another profile that slid into the space in a crash/issue/or update reboot and it created another default profile. A crash log was sent to apple by default

This becomes more apparent when it opens the wrong profile at start. What's interesting is, it shows up sometimes. Attached is an image of mine - two profiles. Mine normal one and the new one now show in the fresh profile, but not in my profile loaded window. 

The first time this happened, all the profiles had the same colors so I thought I lost it. Later I found that profile. This one I was a bit more ready with different themes

<img width="139" alt="Image" src="https://github.com/user-attachments/assets/686e96fa-18ac-4892-84b1-e53984846ea3" />

<img width="141" alt="Image" src="https://github.com/user-attachments/assets/81ef0582-2eb9-4d17-864b-12339ef0a845" />

<img width="442" alt="Image" src="https://github.com/user-attachments/assets/6b6257ee-ba24-43de-aa74-43e4c76b173b" />

<img width="2873" alt="Image" src="https://github.com/user-attachments/assets/53ae7fbf-22e1-4734-9643-5fcf94031704" />
