### ISSUE TITLE
Glitchy 2x pixel density visual issue

### ISSUE THREAD

**Issue by bravecrayon** [zen-browser/desktop#440]
### What happened?

I'm on a Mac using the Apple Studio Display running at 2560x1440 at 2x pixel density (Retina). Many things appear to be about 1.5x pixel density until you rollover them. This doesn't happen in FireFox. I've included two GIFs demonstrating the issue.

![CleanShot 2024-08-22 at 09 23 16](https://github.com/user-attachments/assets/700b3566-a179-41b7-8d0d-6401bb1d75d0)

![CleanShot 2024-08-22 at 09 24 29](https://github.com/user-attachments/assets/24e09d20-ecd7-45a8-8c08-55b62ca1cad6)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27 

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by TomFaulkner** [comment]
I'm seeing the same for all text on Linux.
![image](https://github.com/user-attachments/assets/2ac44a93-4f40-48ba-aa84-d18379871f28)

**Comment by tangowithfoxtrot** [comment]
I'm on macOS, and I also have a 5120x1440p (32:9) monitor, and noticed that the blurry font manifests itself if you make the window width wider than ~4080 pixels (based on my imprecise usage of the responsive design tool). The _webview_ itself can stretch wider than this width, but if the browser window gets wider than that, the fonts become blurry. Reducing the window width makes the fonts clear again.

https://github.com/user-attachments/assets/311b0a17-478e-4c96-89f1-bb448b0a0862

**Comment by jessedobbelaere** [comment]
Can confirm that I see the same behavior as @tangowithfoxtrot on my MacOS with an LG Ultrafine 5K monitor (set to 2560x1440 resolution with @2x but the native resolution is 5120 x 2880). 

When I open a Wiki page with Zen, and make the window larger than `2046px@2x` it switches to blurry text rendering. It's as if there's a breakpoint. Some text is sharp, some is blurred.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/69a5aefd-da44-4e45-b69f-079ebc535696">

When making the browser half of the screen width (2045px or smaller) its crisp text

![Screenshot 2024-08-26 at 14 51 20@2x](https://github.com/user-attachments/assets/e962f873-fcd7-4371-8d83-49d9bd7329bd)

**Comment by bravecrayon** [comment]
Same for me, except it might be <2047 it is sharp. As the window is widened above ~2046 it seems like the text flips between blurry and sharp very quickly, but always finally lands on blurry.

On a hunch, I thought if I could find a high resolution test pattern it might show up when it becomes blurry. I found one, and it is pretty evident in the horizontal resolution pattern. It can be seen that the thin lines become blurry. Also, it can be seen that blurriness actually isn't a static effect because the interference pattern changes as the width of the window changes. I created this to demonstrate: https://codepen.io/bravecrayon/full/MWMXpoa.

**Comment by TomFaulkner** [comment]
I can't tell with the test pattern, but making the window smaller helps significantly.

**Comment by NyxErinys** [comment]
Wanted to jump in here with some more pictures and say same thing happening in Gnome (Wayland) on Arch linux
![Screenshot from 2024-08-28 15-47-01](https://github.com/user-attachments/assets/736ad126-68b1-4e4c-99e5-0ba37f52ea13)
![Screenshot from 2024-08-28 15-46-53](https://github.com/user-attachments/assets/59444a3f-23a3-4e31-939e-85bfa139ae72)

**Comment by krabf** [comment]
I've been having the same issue ever since I started using Zen browser, especially on YouTube and it's definitely annoying. I'm also using a Mac with Studio Display. I have to scroll through the entire page or reload for it to fully render/remove the blurred out texts. Hopefully this will be fixed.

![zen-browser-blur-issue](https://github.com/user-attachments/assets/13dffa79-d19d-4540-97f4-b30393491b08)

**Comment by osborng** [comment]
Same issue for me as well. Mac with Studio Display.
Example page text at full screen
<img width="891" alt="image" src="https://github.com/user-attachments/assets/a3ffa13a-73ee-4e57-b51c-510044b83c15">
Example page text at full screen after moving mouse over the text
<img width="897" alt="image" src="https://github.com/user-attachments/assets/0c7ca975-4e03-4276-96d9-7ab1eb55380e">

**Comment by bravecrayon** [comment]
I know the issue hasn't been addressed or worked on, but I thought I'd just mention I updated to 1.0.0-a.39 today and it's still a thing.

**Comment by HarryHeres** [comment]
Thank you for keeping eye on things! We will get to this as soon as possible, but there are still issues that require our prior attention.

**Comment by flick9000** [comment]
Same is happening to me, switched from Chromium to Zen.
### ZEN :
![ZEN](https://github.com/user-attachments/assets/503c66d9-0143-46cb-a725-d7aa08d507df)
### CHROMIUM:
![CHROMIUM](https://github.com/user-attachments/assets/bc947806-a7e6-4a60-b743-5af816e48ab5)

**Comment by mauro-balades** [comment]
I wonder where all these blurry fonts and pixel density issues come from... Probably touched the wrong rendering config... Ill take over this one, as it seems to annoy people a lot.

**Comment by mauro-balades** [comment]
Would like to ask anyone if setting these values in `about:config` *help* with the issue:

```
gfx.font_rendering.cleartype_params.rendering_mode = 5
gfx.font_rendering.cleartype_params.enhanced_contrast = 1 
```

**Comment by osborng** [comment]
I just tested those settings and still experiencing the same issue.

**Comment by hadiskeini** [comment]
> Would like to ask anyone if setting these values in `about:config` _help_ with the issue:
> 
> ```
> gfx.font_rendering.cleartype_params.rendering_mode = 5
> gfx.font_rendering.cleartype_params.enhanced_contrast = 1 
> ```

@mauro-balades Before you search for any recent changes causing the issue: I just tested the very first macOS build available here (1.0.0-a.2) and the issue is _already_ present there.

**Comment by mauro-balades** [comment]
And Firefox doesn't have this issue?

**Comment by hadiskeini** [comment]
Correct, Firefox and other derivatives don’t have the issue.

**Comment by m-j-r** [comment]
Suggest that this is a duplicate of #383

**Comment by bravecrayon** [comment]
@mauro-balades 
> Would like to ask anyone if setting these values in `about:config` _help_ with the issue:

Tried these settings to no effect. Restarted Zen after setting them to be sure.

If it helps, I noticed that it doesn't seem to be just an issue of blurriness. If the window is resized slowly, the rendered elements and fonts "dance" or "jiggle" as well.

![CleanShot 2024-09-11 at 09 26 02](https://github.com/user-attachments/assets/7e899318-4496-435f-86f5-e99f58049fa0)

**Comment by maxsteenbergen** [comment]
This is all some subpixel rounding issue, it seems

**Comment by mauro-balades** [comment]
Im kindof getting lost in here. In what os does this happen?

**Comment by mauro-balades** [comment]
Does changing `layout.css.devPixelsPerPx` to `2` do something?

**Comment by hadiskeini** [comment]
Unfortunately not. `2` corresponds to the default scaling of the browser, and even changing it to `1` or `3` does not impact the issue.

**Comment by mauro-balades** [comment]
MY suspicion is that it comes from here

https://github.com/zen-browser/desktop/blob/main/src/browser/app/profile/zen-browser.js#L144-L150

**Comment by Obamium69** [comment]
@mauro-balades I tried disabling hardware acceleration but the issue was still present.
Here is my "Graphics" section:
![Bildschirmfoto_20240914_114639](https://github.com/user-attachments/assets/179694da-e296-41ad-b328-02ae205e5375)
![Bildschirmfoto_20240914_114703](https://github.com/user-attachments/assets/9c5b6f11-b970-479c-9a9a-c61a60646f84)
![Bildschirmfoto_20240914_114802](https://github.com/user-attachments/assets/17e61e5f-49b6-40ef-a3e2-5a589136498c)

**Comment by mauro-balades** [comment]
> I tried disabling hardware acceleration but the issue was still present.

Could you disable all the options I showed above and restart? Or did you did that already?

**Comment by Obamium69** [comment]
> > I tried disabling hardware acceleration but the issue was still present.
> 
> Could you disable all the options I showed above and restart? Or did you did that already?

I disabled all the options, that are visible in your screenshot and the issue was there.

**Comment by mauro-balades** [comment]
pffff, this is truly being a nightmare.... The problem is that I dont even know what's casuing it...

**Comment by hadiskeini** [comment]
@mauro-balades Good news, I found the issue!

Tbh I barely know what I'm doing (not a dev), but I went ahead and inspected the Zen browser UI DOM and CSS to experiment whether there's any object or styling causing the issue and here is what I found:

![Screenshot from 2024-09-14 14-38-23](https://github.com/user-attachments/assets/c29ff934-074e-438c-a136-311786fce390)

The issue is with `clip-path: inset(-5px -5px -5px round var(--zen-webview-border-radius, var(--zen-border-radius)));`.

The variable `var(--zen-border-radius)` in particular causes the blurriness. It has the value of `10px` and it seems that any value other than `0px` here will cause the bug.

**Comment by mauro-balades** [comment]
That's crazy because for the next release, i've managed to do rounded corners without clip-path!

Let's see how it goes. Thanks a lot!!!! <3

**Comment by Obamium69** [comment]
> @mauro-balades Good news, I found the issue!
> 
> Tbh I barely know what I'm doing (not a dev), but I went ahead and inspected the Zen browser UI DOM and CSS to experiment whether there's any object or styling causing the issue and here is what I found:
> 
> ![Screenshot from 2024-09-14 14-38-23](https://private-user-images.githubusercontent.com/4141439/367515473-c29ff934-074e-438c-a136-311786fce390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjIzMTgsIm5iZiI6MTcyNjMyMjAxOCwicGF0aCI6Ii80MTQxNDM5LzM2NzUxNTQ3My1jMjlmZjkzNC0wNzRlLTQzOGMtYTEzNi0zMTE3ODZmY2UzOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMTM1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNkOTczNzczYjI4NmQ4NDhlMjVmYjJmZDM4Nzg5OTNiZTQyMzEyODQxMWU2YjE3ZWYxYjUzYTZkOWYzODAwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ivNhOMAv_Xlpu6x7dwtlmIwUdwVL-XIm_WGBhXv1mU8)
> 
> The issue is with `clip-path: inset(-5px -5px -5px round var(--zen-webview-border-radius, var(--zen-border-radius)));`.
> 
> The variable `var(--zen-border-radius)` in particular causes the blurriness. It has the value of `10px` and it seems that any value other than `0px` here will cause the bug.

Can confirm. This fixes it for me too

**Comment by mauro-balades** [comment]
That's it, releasing today 100%

**Comment by AlexanderArvidsson** [comment]
@hadiskeini You're a genius. Tested on my Linux (i3) desktop by scaling up the window way past my 2 monitors (to get the blur). I first saw this problem on my work Macbook with an ultra-wide.

I toggled off `clip-path` and it works. 
The panel is still rounded, because of the `border-radius`, so is there any reason to use `clip-path`?
Let's see how it works with the next release :tada:

**Comment by mauro-balades** [comment]
> so is there any reason to use `clip-path`?

Becuase on some websites, the browser element overlaped the border radius, even with `overflow: hidden;`. I now use pseudo-elements. Faster (it doesnt use GPU like clip-path), and fixes this issue

**Comment by jessedobbelaere** [comment]
I can confirm that it's fixed on the new version released today (`1.0.1-a`). Go to _About Zen_ to update and restart. 
Thanks all!

**Comment by amagnolo** [comment]
The bug was fixed for me with version 1.0.1-a but it reappeared in 1.0.1-a.7. O.S. is Pop Os

**Comment by amagnolo** [comment]
> The bug was fixed for me with version 1.0.1-a but it reappeared in 1.0.1-a.7. O.S. is Pop Os

The problem was a zen custom theme, see mentioned issue above.

**Comment by shrimpwtf** [comment]
im getting this with zen mods totally disabled. it seems to be fine if the windows smaller, but as i drag the length to about 75% of my screen or more, everything goes blurry.
macos, m3 max.

**Comment by shrimpwtf** [comment]
> > Would like to ask anyone if setting these values in `about:config` _help_ with the issue:
> > ```
> > gfx.font_rendering.cleartype_params.rendering_mode = 5
> > gfx.font_rendering.cleartype_params.enhanced_contrast = 1 
> > ```
> 
> @mauro-balades Before you search for any recent changes causing the issue: I just tested the very first macOS build available here (1.0.0-a.2) and the issue is _already_ present there.
> 
> Edit: I also just tested at which viewport size exactly the issue occurs. Until 2038px width everything is fine, starting from 2039px width the issue is present, and height is not a factor. It's a HiDPI monitor so x2 for actual pixels rendered.

exactly this actually yes

**Comment by Obamium69** [comment]
The issue also reappeared for me. I'm running the version 1.0.1-a.14

**Comment by joelazar** [comment]
Same here! MacOS 15.0.1

**Comment by camillof** [comment]
> The issue also reappeared for me. I'm running the version 1.0.1-a.14

+1 here! was working fine until this version 😢 . Went back to .12 and it's ok

**Comment by bstplyr2401** [comment]
Have the same issue. MacOS 14.2 and Zen version 1.0.1-a.14

**Comment by kmatasfp** [comment]
Same here! MacOS 15.0.1, was fixed and broke again in 1.0.1-a.14

**Comment by littleblack111** [comment]
Same here! Arch BTW(Hyprland), was fixed and broke again in latest

**Comment by huwprosser** [comment]
Sadly same for me:
Adjusting layout.css.devPixelsPerPx depending on the screen I'm using works though.

**Comment by limonkufu** [comment]
Same for me with no zen mods enabled on MacOS 15.0.1 with 1.0.1-a.14 version

**Comment by ferdmusic** [comment]
Same issue with Arch + Hyprland on an ultrawide monitor

**Comment by amagnolo** [comment]
The issue is still happening in Zen 1.0.1-a.19 on Pop Os. Blurred font when the window is large.

**Comment by itpropro** [comment]
Issue is still there on 5120x1440, Ubuntu 24.04
