### ISSUE TITLE
Transparent background on url bar

### ISSUE THREAD

**Issue by twiceamonth** [zen-browser/desktop#4970]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When you open a YouTube video player or any other player in full screen mode, press ctr+l, then close full screen mode, and a URL bar will appear that will not have a background

![Image](https://github.com/user-attachments/assets/3c3d3004-25ce-4341-b7af-44306c08db44)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.4b

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by GJRobert** [comment]
Workaround: close the transparent URLbar and open it with `Ctrl+L`/`⌘L` again?

**Comment by twiceamonth** [comment]
No, it happens only when you open URL bar in full screen mode and then close it, next time you open it not in full screen mode it appears as expected.
And it works only when browser interface template is not hidden

**Comment by GJRobert** [comment]
I mean, I can replicate this issue too, but how about just open it with `Ctrl+L / ⌘L` again to give you back a non-transparent URL bar.
Not a fix, just a bypass.

**Comment by Simply-Jeff** [comment]
yes, it's a definte issue even without css and mods, and happens every time, when using ctrl+t on any full-screen video, 
and also the urlabr positioning is weird and it moves to upper-left corner

![Image](https://github.com/user-attachments/assets/36fa372f-27fb-403d-884d-143cc6c85c03)

**Comment by mr-cheffy** [comment]
Fixed on twilight already

**Comment by ddadiani** [comment]
does this need to be reopened? on 1.8.1b it still happens

**Comment by henrydavl** [comment]
still happen on 1.8.2b (mac version)

**Comment by henrydavl** [comment]
> still happen on 1.8.2b (mac version)

never mind, it's caused by one of zen mods (Cleaned URL bar (v1.0.3)), i disabled it and the window no longer transparent

**Comment by ddadiani** [comment]
> > still happen on 1.8.2b (mac version)
> 
> never mind, it's caused by one of zen mods (Cleaned URL bar (v1.0.3)), i disabled it and the window no longer transparent

i disabled all zen mods and it still happens on windows 1.8.2b

**Comment by eduardoleolim** [comment]
If this issue is reopened, I think the issue #5633 will have to be closed as duplicate.
