### ISSUE TITLE
'Fullscreening'/Opening Glance from Essential Tab will make it Essential as well

### ISSUE THREAD

**Issue by Alintya** [zen-browser/desktop#5234]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When 'persisting' a Glance window that had been opened on an Essential Tab, it will become an Essential Tab itself.
This was not the case on 1.7.4b.

### Expected behaviour

Promote the glance to a regular tab

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.6b

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by JSGRD22** [comment]
I believe this is also the case on pinned tabs

**Comment by jso8910** [comment]
This seems to only happen if you open two glance windows. Just one glance window, even if you switch out of the tab and back, and the intended behavior still happens

**Comment by JSGRD22** [comment]
The same issue happens when right-clicking a link and clicking "split link in new tab" within a glance window

**Comment by mr-cheffy** [comment]
Do you have the "have individual essentials for each workspace" enabled?

**Comment by JSGRD22** [comment]
Here's some more insights from attempts to reproduce:
- If I expand glance from an essential tab, it opens in the pinned tabs space
- If I click "open link in new tab" from within a glance view, it consistently opens the new tab in essentials and destroys the order of the essentials
- If I do the above, and _then_ expand glance from an essential tab, this time, instead of opening in the pinned tab space, it opens the tab in essentials and destroys the order

**Comment by JSGRD22** [comment]
And no, I do not have container-specific essentials enabled

**Comment by JSGRD22** [comment]
While you're here, I would like to add that trying to rearrange an essential tab while a glance view is open is very buggy and usually doesn't work in addition to completely messing up the order of all essentials again, but this was probably reported elsewhere

**Comment by mr-cheffy** [comment]
I see...

**Comment by mr-cheffy** [comment]
*Should be fixed*, i've pushed to twilight, let's see after it finishes building

**Comment by mr-cheffy** [comment]
@Alintya do you know how to open the browser toolbox by any chance?

**Comment by Alintya** [comment]
> [@Alintya](https://github.com/Alintya) do you know how to open the browser toolbox by any chance?

I'm used to chromium debugging tools but i will find out

**Comment by Eatham532** [comment]
>     * If I expand glance from an essential tab, it opens in the pinned tabs space
>     
>     * If I click "open link in new tab" from within a glance view, it consistently opens the new tab in essentials and destroys the order of the essentials
> 
>     * If I do the above, and _then_ expand glance from an essential tab, this time, instead of opening in the pinned tab space, it opens the tab in essentials and destroys the order

The issue might be related to an issue i've been experiencing where clicking open in new tab within a pinned/essentials tab makes the new tab with the same pinned state as the original. (Have not yet created a separate bug report yet for this yet.) 

Even then, this issue is still occurring in 1.8.2b

**Comment by Eatham532** [comment]
Upadte: Am no longer experiencing an issue. The only thing I remember doing is clicking the settings icon which swapped my workspace. Had another similar issue #5458 which also was "fixed" at the same time. Maybe some similarity between the two?

**Comment by mr-cheffy** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=%27Fullscreening%27%2FOpening%20Glance%20from%20Essential%20Tab%20will%20make%20it%20Essential%20as%20well%0A
