### ISSUE TITLE
Gecko RTX HDR for video not working

### ISSUE THREAD

**Issue by Stryxus** [zen-browser/desktop#634]
### What happened?

Gecko pretty much just introduced support for NVIDIA's RTX HDR for videos but, for some reason this does not work under Zen Browser. This is pretty vital for us with HDR monitors since, for the time being at least, there is no native HDR at all in Gecko.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by HarryHeres** [comment]
Try to enable the following settings in `about:config` and restart the browser: 

- `gfx.webrender.overlay-vp-auto-hdr`
- `gfx.webrender.overlay-vp-super-resolution`

**Comment by Stryxus** [comment]
> Try to enable the following settings in `about:config` and restart the browser:
> 
>     * `gfx.webrender.overlay-vp-auto-hdr`
> 
>     * `gfx.webrender.overlay-vp-super-resolution`
> 
> 
> More info here: https://connect.mozilla.org/t5/ideas/add-firefox-support-for-rtx-video-super-resolution/idi-p/26995/page/5

Both are enabled by default.

**Comment by Stryxus** [comment]
> If you turn them off, does HDR generally work? I'm working on a fix for #496, so I'm wondering if this is related.

Sadly, no change, even with a mix of them on and off.

**Comment by HarryHeres** [comment]
Then this might get fixed alongside #496

**Comment by HarryHeres** [comment]
@Stryxus could you try using https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6 to see if it is related or not?

**Comment by mauro-balades** [comment]
Yeah, could you try with that theme enabled?

**Comment by Stryxus** [comment]
> @Stryxus could you try using https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6 to see if it is related or not?

This didn't change anything, tested with mix's of the flags also.

**Comment by HarryHeres** [comment]
@Stryxus Is this still relevant? Try updating to a more recent version of the browser.

**Comment by Stryxus** [comment]
Yea, its still relevant. Through all settings.

**Comment by HarryHeres** [comment]
This is weird. As far as I can tell, HDR should be working without any issues as Firefox supports it. As I'm understanding that correctly, you're not able to get "regular" nor "NVIDIA RTX" HDR working ,right?

**Comment by Stryxus** [comment]
> This is weird. As far as I can tell, HDR should be working without any issues as Firefox supports it. As I'm understanding that correctly, you're not able to get "regular" nor "NVIDIA RTX" HDR working ,right?

Regular HDR isnt supported by Firefox other than on macOS.
RTX HDR doesnt work at all on the latest Zen build with combinations of the HDR flags/settings.

**Comment by HarryHeres** [comment]
Ah, I see. Thank you for the clarification.

**Comment by umarhamzy** [comment]
The issue still persists, super resolution still doesn't kick in.

**Comment by Robot-Inventor** [comment]
I don't have an HDR display, so I haven't been able to verify RTX HDR, but I was able to get Video Super Resolution working by setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true`. This setting might also enable RTX HDR to function as well.

**Comment by BronzeManul** [comment]
> I don't have an HDR display, so I haven't been able to verify RTX HDR, but I was able to get Video Super Resolution working by setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true`. This setting might also enable RTX HDR to function as well.

Chiming in on this because this issue literally almost made me revert my decision to switch from Chrome.
I was having the exact same issues described by Stryxus - RTX HDR inactive, regardless of flags, having the rounded corners extension, etc.

Just tried what Robot-Inventor suggested, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true`.
This was partially successful, but I now get some weird behaviour: 

- RTX HDR is inactive when I open a YouTube page (regardless of being in theater view or default view) 
- RTX HDR becomes active when I make the video fullscreen
- RTX HDR stays active after exiting fullscreen (regardless of being in theater view or default view
- RTX HDR becomes inactive again if I then switch between default and theater view
