### ISSUE TITLE
[Regression 1.8b+] Multiple tab issues regarding extensions

### ISSUE THREAD

**Issue by vicky5124** [zen-browser/desktop#7062]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Reopening #5844

After updating past 1.7.6b to any of the 1.8b and above versions, managing tabs with anything that isn't native completely destroys the browser.

- Obtaining the list of tabs more than once with the extension API makes all the tabs disappear; the API doesn't get any tabs (not even pinned), and the native tab bar stops showing the tabs too; not even new tabs show up. Possibly related issues include:
  - https://github.com/mbnuqw/sidebery/issues/2024
  - https://github.com/zen-browser/desktop/issues/5662

- The tab order is really messed up; trying to switch the position, or selecting tabs with an extension, moves the tab or selects the wrong tab with an offset of N (= number of pinned tabs) positions lower (higher in the list when using vertical tabs, to the left in horizontal) than the provided tab position. Possibly related issues include:
  - https://github.com/zen-browser/desktop/issues/5754
  - https://github.com/zen-browser/desktop/issues/5823
  - https://github.com/zen-browser/desktop/issues/7920

- There's also a HUGE memory leak when pinning a tab, or selecting a tab that underflows the tab position through an extension (managed to get Zen to use up 27 GB of ram in 2 minutes). Only the previous point is a possibly related issue.

- There's also some really odd behaviour with hidden and unloaded tabs that I can't make any sense of, but it appears that trying to hide, unhide, load, or unload tabs through extensions or natively occasionally recreates the tabs entirely, or messes up the metadata in a way that extensions can't make sense of it, which can clear any additional metadata the tab may have from the extension (such as which tab tree it is at, what folder it is at, last access time, title, etc...), or make the tab disappear from the extension; this issue is especially bad on pinned tabs. Possibly related issues:
  - https://github.com/zen-browser/desktop/issues/5831
  - https://github.com/zen-browser/desktop/issues/5754

- Other possibly related issues:
  - https://github.com/zen-browser/desktop/issues/5869

- Video demonstration of some of the issues:
  - https://github.com/zen-browser/desktop/issues/10871

The issues listed above are OS-agnostic.

All the issues listed are present with an entirely new profile, no mods, and any one of the listed extensions below.

Everything works perfectly fine in 1.7.6b, but everything is broken on 1.8b and newer versions. None of the patches and fixes in the following releases seem to fix any of the issues, outside pinned tabs duplicating.

I have tested all the tab management extensions that I know of:

- Sidebery (Firefox)
- Sidebery (Zen) (regardless of the presence of the mod)
- Tree Style Tab
- Tab Stash
- Tabby
- Tree Tabs

These issues do not happen on any Firefox version (tested from 133.0 release to 138.0a1)

### Version

1.8b 1.8.1b 1.8.2b 1.9b 1.9.1b 1.10b 1.10.1b 1.10.2b 1.10.3b + Twilight

### What platform are you seeing the problem on?

Linux (AppImage), Linux (Tarball), Windows - x64

### What component is this issue related to?

Extensions

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Might had been fixed with https://github.com/zen-browser/desktop/pull/7064. Could you please check again on twilight?

**Comment by unkn0wncode** [comment]
> Might had been fixed with [#7064](https://github.com/zen-browser/desktop/pull/7064). Could you please check again on twilight?

on latest 1.10.3t (Firefox 137.0) (2025-04-01) (aarch64) in sidebery tabs are still completely not visible.
Restoring any session from third party addons like sidebery and then closing the window also results in freeze and crash.

**Comment by Artii-G** [comment]
It seems that this issue is old and hasn't been addressed. I use Sideberry, as it is still the best tab management tool ever. Making a mess with tabs is terrible for workflow. I previously used Floorp but stopped because it has issues with loading certain websites, and the bugs are not being resolved. If the Zen developers don’t care about fixing this issue, I will leave it immediately.

**Comment by vicky5124** [comment]
The issue persists on the latest version of the browser (1.12.6b), and it still prevents anyone using the extensions to be able to update past 1.7.6b

**Comment by itskagee** [comment]
Still present in 1.12.7b.

Unfortunately, I don't think the devs intend on fixing this. There has been no communication from them whatsoever regarding this.

I feel like it's not compatible with the changes they made to workspace containerization a while ago.

**Comment by lmBored** [comment]
> Still present in 1.12.7b.
> 
> Unfortunately, I don't think the devs intend on fixing this. There has been no communication from them whatsoever regarding this.
> 
> I feel like it's not compatible with the changes they made to workspace containerization a while ago.

No. Apparently, the devs don't want sidebery in zen, their current sidebar development already shows the intention of replacing sidebery (And in zen discord, Cheff - main dev of zen, also told people to just don't use sidebery)

**Comment by D1yt** [comment]
> > Still present in 1.12.7b.
> > Unfortunately, I don't think the devs intend on fixing this. There has been no communication from them whatsoever regarding this.
> > I feel like it's not compatible with the changes they made to workspace containerization a while ago.
> 
> No. Apparently, the devs don't want sidebery in zen, their current sidebar development already shows the intention of replacing sidebery (And in zen discord, Cheff - main dev of zen, also told people to just don't use sidebery)

Then I'm perfectly fine with using Floorp + Sidebery and never looking back. This is not my vision of open-source-projects.

**Comment by itskagee** [comment]
> > Still present in 1.12.7b.
> > Unfortunately, I don't think the devs intend on fixing this. There has been no communication from them whatsoever regarding this.
> > I feel like it's not compatible with the changes they made to workspace containerization a while ago.
> 
> No. Apparently, the devs don't want sidebery in zen, their current sidebar development already shows the intention of replacing sidebery (And in zen discord, Cheff - main dev of zen, also told people to just don't use sidebery)

Unfortunate. But if that's the case, then they should just close this issue as 'not planned' so that people here are not stuck in a limbo.

And while I understand that the sidebar _could_ be a replacement for sideberry, it won't be a replacement for many other types of extensions which rely on browser wide tab data, like Tab Session Manager. I use it to keep all my open tabs indexed and backed up, so that I don't lose them if something bad were to happen, or when migrating to a different browser/system.

The sidebar is not a replacement for this, as is evident by multiple cases of currently open tabs being lost during updates. I wish the devs would reconsider (or implement a solution which is just as robust), but if not, then unfortunately I would have to move away from Zen too. I don't want to, but I can't have this unreliability looming over my head on every browser/system update or failure.

**Comment by lmBored** [comment]
> > > Still present in 1.12.7b.
> > > Unfortunately, I don't think the devs intend on fixing this. There has been no communication from them whatsoever regarding this.
> > > I feel like it's not compatible with the changes they made to workspace containerization a while ago.
> > 
> > 
> > No. Apparently, the devs don't want sidebery in zen, their current sidebar development already shows the intention of replacing sidebery (And in zen discord, Cheff - main dev of zen, also told people to just don't use sidebery)
> 
> Unfortunate. But if that's the case, then they should just close this issue as 'not planned' so that people here are not stuck in a limbo.
> 
> And while I understand that the sidebar _could_ be a replacement for sideberry, it won't be a replacement for many other types of extensions which rely on browser wide tab data, like Tab Session Manager. I use it to keep all my open tabs indexed and backed up, so that I don't lose them if something bad were to happen, or when migrating to a different browser/system.
> 
> The sidebar is not a replacement for this, as is evident by multiple cases of currently open tabs being lost during updates. I wish the devs would reconsider (or implement a solution which is just as robust), but if not, then unfortunately I would have to move away from Zen too. I don't want to, but I can't have this unreliability looming over my head on every browser/system update or failure.

@mauro-balades could you confirm if sidebery integration will be a ticket in Zen roadmap?

**Comment by mr-cheffy** [comment]
Not a priority

**Comment by vicky5124** [comment]
The issue is still relevant to the latest twilight.

**Comment by Heyian** [comment]
Yes, this is still relevant.

**Comment by weiluntong** [comment]
Quick question to you guys who are verifying that this is still an issue.

It feels like you guys may be maintaining two versions of Zen. Is that true? One that keeps up to date to verify bugs, and another to maintain stability for normal usage?

If that's the case, how are you doing that? What's your setup? I'd also like to quickly verify bug relevancy, but I also need my browser to be predictable for normal usage, so I've stayed on 1.7.6b because I rely very heavily on "Tab Session Manager", and haven't upgraded.

Again though, I'd like to validate bugs that I'm tracking too with each new release to try and help.

**Comment by vicky5124** [comment]
I use Linux to verify, I have `zen-browser` installed as 1.7.6b, and `zen-twilight` that I keep updating installed somewhere else (both in /opt), in `/usr/bin` I can just symlink to both install binaries with different names.

**Comment by weiluntong** [comment]
Would this get wonky with configs and settings stored in shared locations? I'd assume both instances would want to try to write to the same location. Such as the Firefox profiles directory? I'm not thinking of other folders that are stored outside the the Firefox install location, but I imagine there are, and would those get super weird with two different installs touching them?

**Comment by vicky5124** [comment]
Just have each instance use a different profile; in `about:profiles` you
can set up multiple profiles, and use a different default for each installl
of the browser

**Comment by vicky5124** [comment]
The issues persists in the latest version.

**Comment by Heyian** [comment]
Yes this is issue is still happening.

**Comment by lmBored** [comment]
Oh, I'm really happy to see this issue finally gets moved to ToDo in the roadmap! I'm looking forward to getting out of Zen 1.7.6b haha, I know I could switch to firefox, but I love Zen for its extensions/features.

**Comment by mia-riezebos** [comment]
still relevant to 1.15.5b

https://github.com/mbnuqw/sidebery/issues/2227

https://cloud.mia.cx/s/6ikCmCzrj8optAH

**Comment by mia-riezebos** [comment]
pinning and unpinning from addons also presents strange behaviour

https://github.com/mbnuqw/sidebery/issues/2227#issuecomment-3305563593

**Comment by Fred-Vatin** [comment]
I’m waiting for zen to be fully compatible with sidebery to switch from Firefox. This extension is just tied to my workflow and tab/panels management.

@erudition in #891 made a better sidebery integration but it only works in current session and need to be reloaded at each startup. Check [zen-sidebery-mod](https://github.com/Erudition/zen-sidebery-mod). This is a lead. We would need this kind of integration permanently.

**Comment by mia-riezebos** [comment]
![image](https://github.com/user-attachments/assets/fc290ec7-7fec-4d74-83d1-0497cffec116)

**Comment by Fred-Vatin** [comment]
> There’s no plans on supporting addons like sidebery, mainly because there’s no need to

- Do they mean because zen already provides the same features ? (it doesn’t)
- Do they mean sidebery is currently integrated with no issue ? (more than one issue are open complaining about sidebery being mostly broken in zen)

<img width="80" alt="image" src="https://github.com/user-attachments/assets/4b5f2a9c-4515-4891-b6f0-c0adaaa331ba" />

**Comment by mr-cheffy** [comment]
> Do they mean because zen already provides the same features ? (it doesn't)

Zen's whole approach to tabs is fundamentally different from Firefox. Extensions like Sidebery are designed specifically for Firefox's tab model, APIs, and assumptions. Zen doesn't use that same system at all, so something like Sidebery wouldn't even know how to “see” or interact with Zen's tabs.

That's why there's no plan to support it, not because “we already have the same features,” but because Zen is built around its own tab architecture that simply isn't compatible with Firefox extensions. Instead, we focus on building those kinds of features natively, in a way that fits Zen's unique design.

**Comment by mia-riezebos** [comment]
Would you welcome PRs that create similar functionality? Tree based tab management most of all.

Even if it's hidden behind a toggle for power users?

**Comment by mr-cheffy** [comment]
It would really come down to how hard it would be to maintain. 

Zen already has its own philosophy on how tabs should work, and I'm not sure tree-style tabs would have much meaning in that context. The whole idea of Zen is to keep tab management simple and consistent, whereas tree structures tend to add a layer of complexity that goes against that. 

Even if it were hidden behind a toggle, it risks becoming a parallel system that needs ongoing maintenance and testing, which could slow down development of the core experience.

**Comment by mia-riezebos** [comment]
Mainly the reason I ache for tree tabs is cause I'm a chronic "open in background tab" clicker.

I end up with massive lists of tabs that I don't want to close but when I wanna do something else (in the same topic or space) I just wanna collapse the group, unload it, and come back to it later.

Groups are cool but are high friction. A tree and branches appear automatically through normal browsing.

**Comment by mr-cheffy** [comment]
Why not just open it in a glance tab?

**Comment by mia-riezebos** [comment]
Tree style tab management is like breadcrumbs. It keeps track of my train of thought. Keeps my context small, to prevent overloading of my working memory.

And it allows for "open mode" thinking. Going down all avenues.

**Comment by mia-riezebos** [comment]
> Why not just open it in a glance tab?

Glance tabs aren't the same as "open in background tab"
I want to keep multiple branches from the trunk open. Like bookmarks (which also have recursive folder structures) but less permanent, more fleeting.

Glance also doesn't keep track of my train of thought, like the "breadcrumb" nature of tree tabs does.

**Comment by mia-riezebos** [comment]
Does zen's tab management have an API that I could build a WE for? I understand it might not be part of zen philosophy but zen is more than just its tab management so I can't achieve the same result just running Firefox with sidebery and userchrome

**Comment by mr-cheffy** [comment]
Not yet due to possible security, privacy and standard concerns we have

**Comment by mia-riezebos** [comment]
I suppose I could look into Sine mods for this as it might require lower level modifications rather than just running in the sidebar

**Comment by mr-cheffy** [comment]
I suppose, yeah. But that's out of my control now

**Comment by mia-riezebos** [comment]
> I suppose, yeah. But that's out of my control now

Thanks for the discussion anyway. Glad to feel heard at least. Even if it's not something that will be zen native I did wanna make my stance heard and explain *why* zen's current tab management is inadequate for my needs.

**Comment by mr-cheffy** [comment]
The main issue really is that tab management extensions for firefox are meant to be *for firefox*. They don't have the concepts of workspaces, empty tabs, glance, folders, etc. So they just get confused about it.

But im happy for solutions, if you have one

**Comment by mia-riezebos** [comment]
The thing I'm missing the most is just when I "open in new tab" it attaches to its parent tab, and that parent is treated as a "group" that I can collapse.
That, but recursively would be great but just one or two levels would already be amazing.

That automatic branching is just the most intuitive way of grouped browsing for me.

**Comment by mr-cheffy** [comment]
I understand, but realistically, what can we do about it?

**Comment by mia-riezebos** [comment]
Just how I described it, either expand tab groups to allow for tabs to be a group's parent, or add the automatic branching. Likely still behind a toggle cause I imagine it's a pretty divisive workflow philosophy.

Another "solution" would be a forktree where zen's Firefox patches are maintained separately. So we can have a Firefox with fixed gradients and working HDR, etc. But still keep tab management addon compatibility...

Though separating all of that out at this stage would be madness.

**Comment by mr-cheffy** [comment]
The thing is, with our limited resources, it's very unrealistic for us to properly maintain an entirely new tab management system, especially one we don't fully believe in as a direction.

Splitting it out into something like a forktree would just multiply the work and make it harder to keep things consistent and stable.

**Comment by mia-riezebos** [comment]
I don't think the tree tabs would be an entirely different system, more of an addition on top of what's already there.

It wouldn't replace spaces, get rid of glance, or mess with pins or essentials either.

**Comment by Fred-Vatin** [comment]
I could be wrong, but I get the impression that there's a gulf between those who've tried sidebery and those who haven't. Everything Mia says is true, the tree tabs is a game changer. There's no turning back once you've tasted it. Of course, it is too soon but in the long run, an API to allow Zen dev to add some features to tabs management would be an asset.

**Comment by lmBored** [comment]
is it possible to maybe have an option to use default firefox tab manager instead of zen's, or is that too complicated to implement?

**Comment by mr-cheffy** [comment]
Zen's entire philosophy is wrapped around it's unique tab management, so no unfortunately.

**Comment by forivall** [comment]
Another tree style tab issue to highlight, with an in-depth investigation from TST's maintainer: https://github.com/piroor/treestyletab/issues/3781#issuecomment-3301270880

**Comment by mr-cheffy** [comment]
It does
