### ISSUE TITLE
Unable to reorder essentials - dragging puts them at the end

### ISSUE THREAD

**Issue by wojciech-kulik** [zen-browser/desktop#7473]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I think it is a regression issue, before the last ~2 versions it was working without any issues, but now I'm unable to reorder my essential tabs, please see the video:

https://github.com/user-attachments/assets/4b7b5ffa-c939-4e1e-a326-ed5406a931b5

### Version

1.11.1b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by mikejones3** [comment]
Same issue here

**Comment by thealkaizer** [comment]
I have the same issue.

I cannot reorder them to the left. Meaning, I can't take the third essential, and drag in first position. It just snaps back to its initial state.

However, I can reorder them to the right, meaning I can move the first essential and move it towards the right. But it sometimes goes into the wrong position. And after a while, I haven't found the trigger, they go back to the wrong order.

https://github.com/user-attachments/assets/ede8251b-b834-42ae-a275-471e2701f9ce

FYI, I'm on Windows 11.

**Comment by mikejones3** [comment]
Trying to add more info to help debug this.. Anything else I can grab? 

I am using container tabs if that could be part of it.

**Comment by Propheticus** [comment]
Would be very useful to have a smoking gun; settings or combinations of settings that cause this.

You could try a new clean profile (`about:profiles`) to see if that has the issue. If it doesn't, slowly add settings / extensions step by step until you see the issue.

**Comment by mikejones3** [comment]
I just tried restarting with adons disabled and that did not help.

**Comment by mikejones3** [comment]
I crated a new clean profile and the issue is not in the new profile... Now is there a way to compare the profiles to see whats different?

**Comment by mikejones3** [comment]
Looks like more users are reporting this on Reddit: https://www.reddit.com/r/zen_browser/comments/1k3xv04/essentials_tabs_rearranging_seems_broken/

Some of the comments are pointing towards container specific essentials enabled  causing the issue. 

Hope this helps with the investigation.

**Comment by Propheticus** [comment]
It's interesting to see several people reporting they no longer see the issue when they turn it off.
The other way round I cannot invoke the issue simply by turning it on though. There might be a combination with other variables.

E.g. are you also on MacOS?  
I'm not seeing it on Win, and another Redditor mentioned not seeing the issue on Linux. (ofc. we're going on single datapoints here, so not jumping to a conclusion yet)



> I crated a new clean profile and the issue is not in the new profile... Now is there a way to compare the profiles to see whats different?

Whenever I want to compare 2 files I use Notepad++ with the ComparePlus plugin. Another good option is Beyond Compare.
In this case mainly the `prefs.js` file from both profiles or the report text from `about:support` could be interesting.

**Comment by Crossbitume** [comment]
> E.g. are you also on MacOS? I'm not seeing it on Win, and another Redditor mentioned not seeing the issue on Linux. (ofc. we're going on single datapoints here, so not jumping to a conclusion yet)

I'm on windows and I have the issue. 

So far I have tested : 
- disabling workspace specific essentials, which works without needing to restart Zen
- disabling themes, doesn't work
- disabling extensions, doesn't work
- changing toolbar layout, doesn't work

Someone mentionned checking logs, where could I see logs relevant to moving essentials ?

**Comment by wojciech-kulik** [comment]
One more detail: this issue occurs in my first workspace, but not in the second one. 

I also suspect that it might be some issue with the sidebar state file. Pinned tabs were also broken in the past (#5754) and reordering wasn't working correctly. Maybe something was saved incorrectly in the state at that time (like an index or something), and this issue is the result.

**Comment by thealkaizer** [comment]
> One more detail: this issue occurs in my first workspace, but not in the second one.
> 
> I also suspect that it might be some issue with the sidebar state file. Pinned tabs were also broken in the past ([#5754](https://github.com/zen-browser/desktop/issues/5754)) and reordering wasn't working correctly. Maybe something was saved incorrectly in the state at that time (like an index or something), and this issue is the result.

I can confirm that in my case, the issue is present on my second workspace, but not the first one. I also use Essentials per Workspace.

**Comment by KronosTopaz** [comment]
I've also run into this issue, was about to make a bug report but found this first.
For me this only happens on some workspaces.
The issue happens in:
- Workspace 1 (No container assigned)
- Workspace 3 (Container assigned)

But the issue does not happen in my second workspace where it also has a container assigned to it.

I'm on Win 11 - Zen version 1.11.5b

**Comment by AlexanderArvidsson** [comment]
I've got this problem on Linux as well, but contrary to some others, it happens in the opposite setup:
1. First workspace is containerless, has the issue.
2. Second workspace is "Work"-container'd. Does not have this issue.

I'm on Linux, 1.11.3b

**Comment by mr-cheffy** [comment]
This should be fixed on 1.12b 👍🏽. Please do test on twilight right now to make sure

**Comment by mikejones3** [comment]
Just downloaded the latest release. Excited to try this and hopefully no errors :-)

**Comment by wojciech-kulik** [comment]
Using the latest version reordering works as expected. Thank you 🎊 !

**Comment by stevechen** [comment]
I'm on Mac OS X with Zen 1.12.10b, and I still see the same issue.
