### ISSUE TITLE
Magic Mouse swipe does not change workspaces on macOS

### ISSUE THREAD

**Issue by wojciech-kulik** [zen-browser/desktop#7713]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When I horizontally swipe using one or two fingers on magic mouse in sidebar area, the workspace is not changed. This behavior slows down daily work with Zen a lot :(.

AFAIK, one-finger horizontal swipe is basically horizontal scrolling, so the sidebar could detect that accordingly. This feature works without any issues in Arc.

**Workaround:**

This feature works only if "Swipe between pages" is enabled which many users turn off because it often triggers unexpected navigation:

<img width="682" alt="Image" src="https://github.com/user-attachments/assets/50c9c4a2-8584-467d-a148-6a266c863f8a" />

### Version

1.11.4b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Workspaces

### Relevant log output if applicable

```shell

```

**Comment by egla89** [comment]
neither does side-scrolling on the MX Master

**Comment by Propheticus** [comment]
@egla89 there's a separate issue open for that https://github.com/zen-browser/desktop/issues/7234

**Comment by 27leaves** [comment]
While this may seem like a non-issue for a lot of people, for me personally this is the thing that bugs me the most in my daily use of the browser. Just putting that out there with a deep appreciation for all the amazing work that's been done here!

**Comment by Elmosh** [comment]
Any update here? I have been reporting this for months on discord

**Comment by Elmosh** [comment]
The workaround as @wojciech-kulik explained is not really a solution, this is a broken implementation, we shouldn’t have to enable Swipe between pages for this to work, enabling this makes browsing unstable as each horizontal scroll triggers a back or forward action in the browser instead of actually scrolling!
It should work like all other browsers with normal scrolling, like arc.

**Comment by beau-at-asi** [comment]
Ideally, implementing any form of horizontal scrolling would be a gamechanger here. For me personally, it is the ability to use the side scroll wheel on my MX Master, but even the "standard" Shift+scroll would be acceptable. It is the only feature from Arc that I simply cannot live without now!

**Comment by liziq** [comment]
Same problem here. Swipe between pages is always enabled but switching between workspaces doesn't work on the Logitech mouse with horizontal scroll wheel.
Use that function all the time so it's quite important to have that working.

**Comment by joshangehr** [comment]
This issue is still relevant, please keep it open—major UX improvement opportunity.

**Comment by ksmithut** [comment]
This issue is still a problem for me. I resorted to getting a trackpad for the time being but would like to get back to using my mouse.

**Comment by Tengusama** [comment]
I am on Windows, with a Corsair Scimitar, and I also cannot scroll between workspaces using any modifier+scroll up down. Worked one day, didn't the next. 

Not a HUGE deal, I can just click the workspace icon, however it was a much smoother, streamlined and fast experience being able to scroll between them. Really felt like it aligned with the overall philosophy and intention of the browser. So it stands out that it is missing.

**Comment by dansauve** [comment]
Problem for me with a Magic Mouse on Mac. The gestures work with the built-in trackpad on my MacBook Pro, but not with the mouse ;-(

**Comment by mrcoder991** [comment]
I think it is fixed now, it works for me. Anther can close this issue.

**Comment by Elmosh** [comment]
no, it’s not fixed. Still same exact issue

**Comment by mrcoder991** [comment]
yeah you are right @Elmosh, I never bordered to turn that `swipe between page` off.

**Comment by griiid** [comment]
Start using Zen browser yesterday, I need this, too.
(I use Logitech mouse)

**Comment by Brian-Pob** [comment]
I still have this issue. Gestures don't work with magic mouse but they work with the macbook trackpad

**Comment by kayrunm** [comment]
This is the one thing that's stopping me from migrating to Zen from Arc

**Comment by Andresshamis** [comment]
Hi I tested my PR using MX Master 3S and it works great. Hope your testing goes well id love to see this live! First open source contribution

**Comment by Andresshamis** [comment]
@mr-cheffy please review this PR when you have time. I appreciate your work! This should fix it once and for all for all horizontal scroll devices like MX Master series, and Apple Magic Mouse.
