### ISSUE TITLE
The vertical TAB bar does not respond to touch input

### ISSUE THREAD

**Issue by Starry-AXQG** [zen-browser/desktop#8103]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When you scroll the TAB page with your finger, the TAB does not scroll. In the Compact Mode, clicking the edge of the screen with your finger also fails to evoke the vertical TAB bar.
At first, I thought it was the browser lagging, but I tested it many times and it seemed to have no response. I compared and tested Firefox, chrome  and Micorosoft edge browser. Their vertical TAB bars respond well to touch input. On edge browser, you can slide your finger to scroll the TAB page. If the TAB bar is in a folded state, you can click the TAB bar and make it temporarily expand, and it will automatically refold when it loses focus.

### Version

1.12.1b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by Bu156** [comment]
Same thing here on Zen 1.12.1b on a Surface Pro 7 running Debian 13. Apart from this the browser works really well with just touch so if this were fixed it would be perfect for me.

**Comment by Starry-AXQG** [comment]
> Same thing here on Zen 1.12.1b on a Surface Pro 7 running Debian 13. Apart from this the browser works really well with just touch so if this were fixed it would be perfect for me.

You're right. It seems that zen was ill-considered from the very beginning when developing vertical tabs. Touch support is a rigid requirement for some devices, such as all-in-one computers and tablets running the Windows system,which often directly use touch input instead of a mouse.As for me, when I stream on a mobile device, I need touch input and I simply don't have a mouse at hand.

**Comment by Zhanyuanium** [comment]
This problem seems already been fixed one or two weeks ago. Zen 1.12.8b (Firefox 138.0.4) on Windows 11 LTSC 2024 on ASUS ROG Flow Z13 2025. Now the vertical tabs can be scrolled smoothly with a finger on a touch screen.

**Comment by Starry-AXQG** [comment]
> This problem seems already been fixed one or two weeks ago. Zen 1.12.8b (Firefox 138.0.4) on Windows 11 LTSC 2024 on ASUS ROG Flow Z13 2025. Now the vertical tabs can be scrolled smoothly with a finger on a touch screen.

Indeed, but the problem still hasn't been completely solved. In compact mode, clicking on the edge of the browser window does not guarantee that the vertical tabs will be correctly activated every time. Sometimes it works, and sometimes it doesn't respond. Furthermore, when the focus is lost, the vertical tabs sometimes can automatically hide normally, while at other times they cannot.

**Comment by Starry-AXQG** [comment]
Currently, the vertical tabs can respond to the scrolling caused by touch input, but for the compact mode, further efforts are needed. Therefore, I will continue to open this issue.🧐

**Comment by Starry-AXQG** [comment]
I conducted a simple test in the compact mode. Although clicking on the blank area of the web page does not enable the vertical tabs to be hidden, clicking on the UI blank area of the browser seems to be able to properly hide the vertical tabs.🧐

**Comment by Starry-AXQG** [comment]
> I conducted a simple test in the compact mode. Although clicking on the blank area of the web page does not enable the vertical tabs to be hidden, clicking on the UI blank area of the browser seems to be able to properly hide the vertical tabs.🧐

I tested Twilight and it seems that these issues have been resolved in the beta version. However, I noticed that, whether it's the release version or the Twilight version, it appears that you cannot open the context menu by long-pressing the blank area of the browser UI. This means that you cannot activate the minimalist mode or customize the theme color in this way.
Besides, this issue has almost been resolved successfully. Well done!

Editor: My previous tests were not rigorous enough. I discovered that the internal pages of the browser (such as about:config or about:blank) behave just like the browser's UI interface. By clicking on the blank area, the vertical tabs lose focus and are hidden. However, for web pages, clicking on the blank area of the web page still does not enable the vertical tabs to automatically hide.
![Image](https://github.com/user-attachments/assets/54a1e1e5-fb1f-4611-8651-365bb91ab385)
