### ISSUE TITLE
Installed mods not showing up in list

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#8394]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When I go to the Mod Store and install mods, they either don't actually install, or they install and show up on the list of installed mods and then disappear the next time you start the browser. After trying at least three times, they only showed up one time, when I restarted the browser, they were gone.
Running 1.12.5b on Arch Linux installed via pacman.

### Version

1.12.5b

### What platform are you seeing the problem on?

Other

### What component is this issue related to?

Mods / Themes

### Relevant log output if applicable

```shell

```

**Comment by AveshLutchman** [comment]
Same issue present on Windows.

In my case all my mods seem to not be active as well.

**Comment by dshan12** [comment]
I have the same issue. I am on windows. I have switched back to arc since I can't use any mods here for the time being.

**Comment by ghost** [comment]
The only mod that worked for me was the Better CtrlTab Panel, and it only worked the first time I tried it. The next time I opened the browser, it and all the others that I had installed were gone.

**Comment by dshan12** [comment]
I got it fixed by doing this: https://www.reddit.com/r/zen_browser/comments/1ft03h2/comment/mh690e4/

**Comment by dshan12** [comment]
The mod that is causing this for me is the SuperPins mod. I tried to reinstall it and then the same issue happened so I uninstalled it and now everything is working as intended.

EDIT: Seems that was just a fluke since when I tried installing it for the third time everything worked as intended.

**Comment by ghost** [comment]
> I got it fixed by doing this: https://www.reddit.com/r/zen_browser/comments/1ft03h2/comment/mh690e4/
@dshan12  That did the trick, thank you.

**Comment by ghost** [comment]
The issue appears to be resolved with ver. 1.13.2b

**Comment by svalbardsleeperdistrict** [comment]
Same issue with the current (1.0.2-b.3) version on EndeavourOS. The suggestion linked from Reddit above did not fix it.
