### ISSUE TITLE
Zen Crashes when handling anything related to audio sharing(discord or call) or video sharing

### ISSUE THREAD

**Issue by Barmanji** [zen-browser/desktop#8553]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

![Image](https://github.com/user-attachments/assets/838310b7-1fa9-4d71-b7af-4a68dfe2acea)

![Image](https://github.com/user-attachments/assets/2c7a9c33-b742-413e-a9d2-5b9a25e9889d)

### Version

latest

### What platform are you seeing the problem on?

Other

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by 0Ky** [comment]
Need more information, can you test using https://mozilla.github.io/webrtc-landing/gum_test.html? Does it crash here as well?

**Comment by Barmanji** [comment]
> Need more information, can you test using [mozilla.github.io/webrtc-landing/gum_test.html](https://mozilla.github.io/webrtc-landing/gum_test.html)? Does it crash here as well?

screenCapture and tabCapture doesn't show me the captured content they just show success, except them others seems to be working fine, even i am shocked why do i get crashes in Discord when talking to someone, even though here it works fine(the microphone testing part)

More platforms that i have witnessed crashes -
Discord (ASAP as i enter in any room)
Cisco WebX (ASAP as entering)
Not in Google meets for some reason, it works fine

**Comment by purpxd** [comment]
This could be related as zen browser was crashing for me last night when I was visiting this site. 

https://us.espres.so/

Does a notification pop up at the bottom for you saying speech dispatcher library is missing? 

Due to speech-dispatcher missing I was getting console errors such as "No such JSProcessActor 'BrowserToolboxDevToolsProcess'"  and "Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved".

After installing the speech-dispatcher library, no more crashes.

**Comment by 0Ky** [comment]
@Barmanji Can't reproduce.

@purpxd Website works just fine, no crashes in a fresh installation on both Linux and Windows.

**Comment by Barmanji** [comment]
> This could be related as zen browser was crashing for me last night when I was visiting this site.
> 
> [us.espres.so](https://us.espres.so/)
> 
> Does a notification pop up at the bottom for you saying speech dispatcher library is missing?
> 
> Due to speech-dispatcher missing I was getting console errors such as "No such JSProcessActor 'BrowserToolboxDevToolsProcess'" and "Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved".
> 
> After installing the speech-dispatcher library, no more crashes.

well guess what now it works fine, i mean [mozilla.github.io/webrtc-landing/gum_test.html-ThisLink](https://mozilla.github.io/webrtc-landing/gum_test.html)? 
Also when i tested it didnt show any thing like speech dispatcher is missing either in console, or down or in any popup.

**Comment by Barmanji** [comment]
> [@Barmanji](https://github.com/Barmanji) Can't reproduce.
> 
> [@purpxd](https://github.com/purpxd) Website works just fine, no crashes in a fresh installation on both Linux and Windows.

Even I can't haha, Well the main problem remains consistent of discord keeps crashing when joining any lobby with people being in that room or webex Cisco.

**Comment by Barmanji** [comment]
well well well @0Ky @purpxd 
turns out i am dumb, and i haven't checked what version i was on, I was on 1.0.2.b.2 (Ancient from novemeber'24) for some reason in my arch (hyprland) yay -Syu and pacman -Syu didn't decide to update all the pacages without anyone being ignored (you can ignore some packages if you dont want to update) also it showed FULL SYSTEM UPGRADED everytime, like OMFG.

Now its fixed and working, sorry for bothering haha.
One more issue arrived though, now when i press Ctrl+T for opening new tab, it opens url bar  and not any default tab, i have seet defualt tab/new tab in settings but it doenst seems to be working.
And yes now i am on latest build ( firefox 139 and ZEN 1.12.8b)

**Comment by 0Ky** [comment]
> One more issue arrived though, now when i press Ctrl+T for opening new tab, it opens url bar and not any default tab, i have seet defualt tab/new tab in settings but it doenst seems to be working.

@Barmanji That's not an issue, it's a feature. Have a look at the [docs](https://docs.zen-browser.app/user-manual/urlbar#enable-legacy-new-tab-mechanism) (New Tabs), you can enable the legacy new tab page by setting `zen.urlbar.replace-newtab` preference to `false`.

**Comment by Barmanji** [comment]
> [@Barmanji](https://github.com/Barmanji) That's not an issue, it's a feature. Have a look at the [docs](https://docs.zen-browser.app/user-manual/urlbar#enable-legacy-new-tab-mechanism) (New Tabs), you can enable the legacy new tab page by setting `zen.urlbar.replace-newtab` preference to `false`.

Also can you tell me how do I make my URL bar content centered, there seems to be a mod before but in updated version its gone.
well closing the issue coz mostly issues are resolved.

**Comment by 0Ky** [comment]
@Barmanji Check [Zen Mods](https://zen-browser.app/mods) for what ever mod you're looking for, if it's not there then create a `userChrome.css` file to add your own custom style to the browser. You can follow step 1 and 2 from the [docs](https://docs.zen-browser.app/guides/live-editing#step-1-access-the-profile-folder) and add the following CSS to center the [floating URL bar](../../theme-store/issues/995):

```css
#urlbar[open][zen-floating-urlbar='true'] {
  position: absolute !important;
  top: 50% !important;
  left: 50% !important;
  transform: translate(-50%, -50%) !important;
}
```
