### ISSUE TITLE
Zen disables compact mode on startup

### ISSUE THREAD

**Issue by mastazi** [zen-browser/desktop#8606]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I keep compact mode constantly enabled. During the last few weeks, when I start Zen, ~~there is a chance that~~ compact mode has been disabled, as if the setting of having compact mode enabled had been reset to default. ~~I don't have a way to reproduce reliably, sometimes it happens and sometimes it doesn't. I think on average I experience this once a day.~~ **_EDIT: as of 1.12.9b this now can be reproduced reliably on every launch._** It started recently, within last 2 weeks, never happened before. I experienced this on all 3 OSes that I use, Linux Mac and Windows.

### Version

1.12.7b 

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```

**Comment by tnnyx** [comment]
I would like to contribute on reproducibility part. 

For me, it always happens when I restart my PC. I'm using Windows.

**Comment by zQueal** [comment]
I'm seeing multiple and significant issues with compact mode. It will randomly disable itself either (again, randomly) the tab bar or address bar. I have to quit the browser to fix it, and sometimes not even that is enough. I have to disable compact mode, force terminate the zen.exe process, and then run the browser again and its fixed...

**Comment by chiefvelo** [comment]
Compact mode is disabled on new window creation and has to be re-enabled manually.

**Comment by Propheticus** [comment]
@zQueal just to eliminate the possibility: you are not unknowingly using the toggle shortcuts?

example (not defaults):

![Image](https://github.com/user-attachments/assets/ddb9a89d-0ffc-4f22-91b2-fa665152c720)

**Comment by mastazi** [comment]
> Compact mode is disabled on new window creation and has to be re-enabled manually.

Interesting, it could be somehow related but in my case I'm not creating a new window, just launching Zen from scratch

> It will randomly disable itself either (again, randomly) the tab bar or address bar.

It doesn't do that in my case, it just turns itself off but the settings for hiding sidebar/toolbar are retained

**Comment by zQueal** [comment]
> [@zQueal](https://github.com/zQueal) just to eliminate the possibility: you are not unknowingly using the toggle shortcuts?
> 
> example (not defaults):
> 
> ![Image](https://github.com/user-attachments/assets/ddb9a89d-0ffc-4f22-91b2-fa665152c720)

I doubt it, but to be sure I've disabled these hotkeys. We'll see how it goes! Thanks.

**Comment by qvap** [comment]
Having the same problem after the latest release from Zen update platform (1.12.8b). As for me, it's seems like compact mode consistently (tbh i can't guarantee) disables after rebooting the system, which can be reenabled without issues. Running on Windows

**Comment by Styphoryte** [comment]
> Having the same problem after the latest release from Zen update platform (1.12.8b). As for me, it's seems like compact mode consistently (tbh i can't guarantee) disables after rebooting the system, which can be renabled without issues. Running on Windows

Figured I'd chime in and say I updated as an existing zen user with tons of tabs open and this most recent update found the same issue where it was disable automatically and my side tabs were not hiding and went to the settings but compact mode was already enabled so I just toggled them on and off. That didn't work so I found this thread and the shortcut Ctrl+Alt+C renable it thankfully.

**Comment by qvap** [comment]
> compact mode was already enabled so I just toggled them on and off. That didn't work

Well, it's seems like this bug have very uncertain behavior, because I can reenable it through the settings without issues. Or maybe I got another not related type of error 😔

**Comment by NYR10146** [comment]
Can confirm this happens on Arch Linux (flatpak) - 1.12.8b.

**Comment by PolarisPyra** [comment]
I run zen browser from the AUR on version 1.12.8B. Its quite annoying it seems happen every time zen closes then opens again opens.

**Comment by IrksomeHighlndr** [comment]
I am currently running Fedora Linux 42, KDE Plasma 6.3.5, 1.12.9b (Firefox 139.0.1) (64-bit) (Flatpak). Every time there is an update or I restart my system, the Compact Mode is disabled by default. Therefore everytime I have to go to settings or right click on the Tabs area to enable compact mode.

**Comment by mastazi** [comment]
Just an update, with the most recent version 1.12.9b the problem has become worse and it now happens every single time I restart Zen. I'm going to update the description above to reflect this.

**Comment by tnnyx** [comment]
Update: It's still happening after installing latest version (1.12.10b). And I can't reproduce the bug anymore.

**Comment by zQueal** [comment]
Still happening with current version and after disabling the hotkeys.

**Comment by Propheticus** [comment]
I cannot reproduce this at every restart of Zen. It's remembered.

I do see it change on<>off, but that's because the theming is synced via my Firefox (sync) profile via the 'add-ons' option which is ticked. On my laptop I have compact mode on, on my desktop with larger (non oled) monitor I want it off. Still the setting is synced between them.
Could Sync be playing a role in your case as well?

**Comment by zQueal** [comment]
>  Could Sync be playing a role in your case as well?

Not saying it explicitly couldn't be, but I only use FF on my desktop. I do have the sync enabled, but I'm not syncing to other browsers so the setting cant be being changed every sync. If that makes sense.

**Comment by shohamc1** [comment]
This happens 100% of the time for me on Windows. FF sync enabled with one other browser on the same machine.

**Comment by Aprilpie** [comment]
Windows 11, a bit inconsistent but stills happens sometimes after restart.

**Comment by jonmarkdeane** [comment]
Same issue. Arch Linux, Hyprland, Zen 1.12.10b.
New windows follow my preference, but if all instances are closed (such as on system restart), then the preference is lost.

**Comment by Propheticus** [comment]
Looks like a fix was committed https://github.com/zen-browser/desktop/commit/b932558ad63e23298a93cbaa67ebcd3d079ab52d
Coming soon ™

**Comment by bustozoni** [comment]
Waiting for it, same thing windows 11, desktop. It does not happen in my laptop though.

**Comment by RockRida317** [comment]
Happens on my Windows laptop too

**Comment by mastazi** [comment]
> Looks like a fix was committed [b932558](https://github.com/zen-browser/desktop/commit/b932558ad63e23298a93cbaa67ebcd3d079ab52d) Coming soon ™

It seems that commit was part of 1.14b release, unfortunately though this is still happening to me in 1.14b

**Comment by maclarel** [comment]
Still happening for me in 1.14b as well.

**Comment by vkpdeveloper** [comment]
Same issue in MacOS too, latest Zen version 1.13.2b (Firefox 139.0.4) (aarch64)

**Comment by Propheticus** [comment]
> > Looks like a fix was committed [b932558](https://github.com/zen-browser/desktop/commit/b932558ad63e23298a93cbaa67ebcd3d079ab52d) Coming soon ™
> 
> It seems that commit was part of 1.14b release, unfortunately though this is still happening to me in 1.14b

Is it still happening every time you restart Zen (even when starting right after closing without a reboot)?

https://github.com/zen-browser/desktop/issues/8606#issuecomment-2934475128
Can we establish whether the issue (after a reboot) happens with Firefox sync off ?

**Comment by maclarel** [comment]
> Is it still happening every time you restart Zen (even when starting right after closing without a reboot)?

I could not immediate reproduce this just _restarting the browser_, but after a reboot earlier today compact mode did disable itself again.

> Can we establish whether the issue (after a reboot) happens with Firefox sync off ?

Recognizing I'm not the person that was asked - I am *not* using Firefox sync.

**Comment by mastazi** [comment]
@Propheticus no reboot needed, as I am also experiencing this issue on a laptop which I never reboot. 

BUT it doesn't happen every time I launch Zen, only sometimes. It seems to be related on how long ago did I last used Zen - if I used it within the last 1-2 hours it doesn't happen but if I used it the day before, then it's more likely to happen.

EDIT sync is on for me, I always keep compact mode on; on all my computers that I'm syncing with.

**Comment by mastazi** [comment]
@Propheticus sorry I have to make a correction. This part of my previous comment is incorrect

 > It seems to be related on how long ago did I last used Zen - if I used it within the last 1-2 hours it doesn't happen but if I used it the day before, then it's more likely to happen

I just experienced the bug and I had closed the browser just  a couple minutes earlier. So ignore this.

**Comment by Propheticus** [comment]
Upon closing Zen, can you confirm you have a `xulstore.json` file in your profile folder? (The location can be found in about:support)

The xulstore contains the state of the compact mode on closure.

<img width="291" height="84" alt="Image" src="https://github.com/user-attachments/assets/c4f40e47-827c-4e0e-a093-96234b1ef2c4" />

 I just rebooted my PC several times and could not get it to disable compact mode. The xulstore was not changed upon reboot (what process would even do that when Zen is not running?) 


> Recognizing I'm not the person that was asked - I am _not_ using Firefox sync.

Still useful information, thanks. You're also not sharing the same profile between Firefox and Zen? (trying to figure out how / rule out that the xulstore.json mentioned above gets overwritten by something else)

**Comment by michaelminuse** [comment]
This is occurring to me as well on the latest build of Twilight on W10 version 22H2; to the point that I customized the toggles to enable compact mode more quickly.

**Comment by michaelminuse** [comment]
> > > Looks like a fix was committed [b932558](https://github.com/zen-browser/desktop/commit/b932558ad63e23298a93cbaa67ebcd3d079ab52d) Coming soon ™
> > 
> > 
> > It seems that commit was part of 1.14b release, unfortunately though this is still happening to me in 1.14b
> 
> Is it still happening every time you restart Zen (even when starting right after closing without a reboot)?
> 
> [#8606 (comment)](https://github.com/zen-browser/desktop/issues/8606#issuecomment-2934475128) Can we establish whether the issue (after a reboot) happens with Firefox sync off ?

I have FF sync off.


> Upon closing Zen, can you confirm you have a xulstore.json file in your profile folder? (The location can be found in about:support)

> The xulstore contains the state of the compact mode on closure.
> Image
> 
> I just rebooted my PC several times and could not get it to disable compact mode. The xulstore was not changed upon reboot (what process would even do that when Zen is not running?)

For me, when I restart the browser zen-compact-mode = true but is only activated in one window.

**Comment by Propheticus** [comment]
> but is only activated in one window

That sounds like #7591 and #7682,  about multiple windows not all recovering their state.

This issue is even worse: the compact mode not restoring at all, even for 1 window.

**Comment by michaelminuse** [comment]
> > but is only activated in one window
> 
> That sounds like [#7591](https://github.com/zen-browser/desktop/issues/7591) and [#7682](https://github.com/zen-browser/desktop/issues/7682), about multiple windows not all recovering their state.
> 
> This issue is even worse: the compact mode not restoring at all, even for 1 window.

Touché.  Apologies for clogging up the thread.

**Comment by maclarel** [comment]
> Upon closing Zen, can you confirm you have a xulstore.json file in your profile folder? (The location can be found in about:support)

Confirming that it is there, and I see this content:

```
    "zen-main-app-wrapper": {
      "zen-compact-mode": "true"
    },
```

I'll double check that this is still set next time I see the issue pop up. Thanks for the lead.

> Still useful information, thanks. You're also not sharing the same profile between Firefox and Zen? (trying to figure out how / rule out that the xulstore.json mentioned above gets overwritten by something else)

Not as far as I know - at least nothing I've configured explicitly. I don't use Firefox regularly (if at all) since moving to Zen.

**Comment by maclarel** [comment]
Just hit this on a different machine (also not using Firefox sync). `xulstore.json` includes this at the time the issue popped up:

```
    "zen-main-app-wrapper": {
      "zen-compact-mode": "-moz-missing\n"
    },
```

After re-toggling this in the Zen UI, closing Zen, and rebooting, I have **not** immediately had compact mode disable itself again 🤔 Still seems to be unclear what causes this, but I'm keeping an eye out for trends!

Update: Just had this happen again on my Mac (example above was Linux) and sure enough, I'm seeing `-moz-missing\n` in `xulstore.json`. Something seems to be resetting this value intermittently.

Update 2: And now again on my Linux machine - reverted back to the same value noted above.

**Comment by tobias-hay** [comment]
Still broken in 1.14.4b (Firefox 140.0.4) (64-bit), windows 11.

**Comment by tommdq** [comment]
Same on Mozilla Zen 1.14b - Arch Linux

**Comment by gtaltatra** [comment]
Still broken in 1.14.4b (Firefox 140.0.4) (64-bit), windows 10.

**Comment by Propheticus** [comment]
@Woofer21, @tommdq, @gtaltatra 
Can you 
- Try in v1.14.5b
-  Indicate whether by 'broken' you mean:
   - the compact mode is not remembered at all for a single window (can't repro on my end) , or;
   - compact mode is remembered for the main window but isn't for additional windows when you had multiple and closed Zen via ctrl+shift+q / '... menu >exit' (can repro*).

*: Oddly, when closing Zen by right clicking the taskbar icon and "close all windows" + upon restarting Zen using ctrl+shift+n to restore the other windows, these do restore with compact mode enabled.

**Comment by tobias-hay** [comment]
> [@Woofer21](https://github.com/Woofer21), [@tommdq](https://github.com/tommdq), [@gtaltatra](https://github.com/gtaltatra) Can you
> 
>     * Try in v1.14.5b
> 
>     * Indicate whether by 'broken' you mean:
>       
>       * the compact mode is not remembered at all for a single window (can't repro on my end) , or;
>       * compact mode is remembered for the main window but isn't for additional windows when you had multiple and closed Zen via ctrl+shift+q / '... menu >exit' (can repro*).
> 
> 
> *: Oddly, when closing Zen by right clicking the taskbar icon and "close all windows" + upon restarting Zen using ctrl+shift+n to restore the other windows, these do restore with compact mode enabled.

- 1.14.5b (Firefox 140.0.4) (64-bit), windows 11
- Yes, ~~main is remembered but none of the others~~ It remembered none of my windows compact state, I have to set it again on all of them
- Zen is getting forced closed by my computer shutting down

**Comment by adamnemet** [comment]
1.14.5b (Firefox 140.0.4) 
It is still an issue on both the latest stable updated Windows 11 and on Mac OS Sequoia 15.5
It does not seem to happen to me after any particular use case. One day it works, than the notebook/macbook remain untouched plugged in and next time I wake it up it will disable compact mode again, not right after waking up or logging back in, but after a while in a random manner. Like once in every 2-3 days. Manually enabling it solves the issue. I can't stand the wide sidebar, that's why I prefer it to be present only when switching between tabs.
I would be happier though to see the title bar on Windows, since it breaks the consistency with the other regular applications that it is also hidden.

**Comment by mr-cheffy** [comment]
Once you restart and it *does not work*, could you please send a screenshot of `zen.view.compact.should-enable-at-startup` in about:config? **DO NOT CHANGE THE VALUE MANUALLY**

**Comment by tobias-hay** [comment]
> `zen.view.compact.should-enable-at-startup`

<img width="1028" height="109" alt="Image" src="https://github.com/user-attachments/assets/147eebba-2ec9-44cb-8920-e0a54864b095" />

**Comment by spslabo** [comment]
>  compact mode is remembered for the main window but isn't for additional windows when you had multiple and closed Zen via ctrl+shift+q / '... menu >exit' (can repro*).

I have had the same issue for a while, I just tested on version 1.14.5b (Firefox 140.0.4) (64-bit) on Arch and it's still happening. 

<img width="1486" height="167" alt="Image" src="https://github.com/user-attachments/assets/c3c22d43-f949-4abc-b0f3-926a37a5f438" />

**Comment by hamidzr** [comment]
same on macos: ==> zen: 1.14.5b (auto_updates)
as in: windows past the main window do no inherit compact mode

**Comment by WOKNz** [comment]
1.14.5b (Firefox 140.0.4) (64-bit), Win 11 26100.4652
The issue is still present, "zen.view.compact.should-enable-at-startup" is "true".

**Comment by dalekirkwood** [comment]
Same issue:

OS: Linux Mint 22.1 x86_64 
Kernel: 6.8.0-63-generic

1.14.5b (Firefox 140.0.4) (64-bit)

**Comment by mastazi** [comment]
Reproduced on 1.14.5b on both Mac Sequoia 15.5 and Linux Pop OS 22.04LTS as well.

`zen.view.compact.should-enable-at-startup` is `true`

Not sure if relevant but I wanted to share that in my settings:

1. "Open Previous Windows and Tabs" is OFF
2. "Continue where you left off" is OFF

**Comment by Propheticus** [comment]
> Reproduced on 1.14.5b on both Mac Sequoia 15.5 and Linux Pop OS 22.04LTS as well.
> 
> `zen.view.compact.should-enable-at-startup` is `true`
> 
> Not sure if relevant but I wanted to share that in my settings:
> 
>     1. "Open Previous Windows and Tabs" is OFF
> 
>     2. "Continue where you left off" is OFF

Don't those settings mean you are presented with an empty view with a floaty URL bar + an expanded sidebar to start your navigation? Does the sidebar not hide again as soon as you enter a search term/url > new tab is opened?

**Comment by mastazi** [comment]
@Propheticus I have "Multiple toolbars", and URL Bar Behaviour is set to "Normal" - this is what I see at initial launch, when there is no bug (sidebar minimised as it should)

<img width="3072" height="1728" alt="Image" src="https://github.com/user-attachments/assets/440a0b65-761d-47fb-9f0c-0efeb5306d44" />

**Comment by mr-cheffy** [comment]
Please stop commenting "same in X...", it's just adding clutter to the issue. Thanks.

Please try tomorrow on twilight and let me know if it's still happening. Note that it remembers compact mode from the last changed window. This means that if you turn off compact mode in one window and then close them all, it will (most likely) turn compact mode for all windows.

**Comment by foss-** [comment]
Just updated to `1.15t (Firefox 141.0) (2025-07-29) (aarch64)`, macOS 15.6 and found the following behavior:

Case 1
- one window open, with a single tab
- press alt + cmd + c (macOS) to switch to compact mode
- close + re-open Twilight
- generally this seems to work but on re-open the focus should probably not be in the search field (⚠️ unexpected)

<img src="https://github.com/user-attachments/assets/a13b2674-aed8-4fde-aef0-fa22b8a5293d" width="250">

- after selecting the tab, that tab loads and Twilight goes back to compact mode

Case 2
- two open windows with each a single tab
- both windows are set to compact mode
- close + re-open Twilight
- both windows are not showing the last open tab (expected) but again focus is in the search bar

<img src="https://github.com/user-attachments/assets/83125b0f-9028-4fba-9f38-2c5407bf1172" width="450">

- curiously when selecting the open tab in window two, the view does not go back to compact mode (⚠️ unexpected)

Hope this is useful feedback @mr-cheffy

**Comment by ali-exacute** [comment]
just to add to this issue (as a feature)
it would be cool if zen remembered which window has compact mode on and which one doesn't

for example, i have zen with some of my tabs on my vertical monitor, as it is 720p, i use compact mode on.
but on my main (1440p) monitor, i don't use compact mode

but every time my PC restart and zen startup, they are both back to default

**Comment by mr-cheffy** [comment]
Sorry about the overlook guys.

I think i've managed to find the issue where XUL store would set the attribute BEFORE we properly restore the session, making this expression RUN and therefor not properly initializing compact mode:

```js
    if (
      this.preference === value ||
      document.documentElement.hasAttribute('zen-compact-animating')
    ) {
      if (typeof this._wasInCompactMode !== 'undefined') {
        // We wont do anything with it anyway, so we remove it
        delete this._wasInCompactMode;
      }
      // We dont want the user to be able to spam the button
      return;
    }
```

This commit should end up on the next release, which *should* fix it. I did the tests and it seemed to have fixed this issue.
https://github.com/zen-browser/desktop/commit/a4b8e2134f5d463c96630dd5e08bb37026e86127

Additionally, i've added the flag `zen.view.compact.debug` so we can properly debug this once it's out.

Again, sorry for the delay!

**Comment by zQueal** [comment]
Appreciate the patch!

**Comment by mr-cheffy** [comment]
After the update, can it still be reproducible?

**Comment by foss-** [comment]
Smoke test yesterday with multiple windows worked as expected. When re-starting Zen briefly noticed un-collapsed sidebar which then animated out. If that is expected, we're good. Also that's a minor issue compared to Zen just not respected / remembering collapsed state correctly before. Thanks so much for your work 🙏

**Comment by mr-cheffy** [comment]
The pref has been renamed so current users don't randomly enable compact mode without knowing, meaning next update you might need to re-enable compact mode, this would be expected to limit the amount of possible 'fake' reports. Please let me know if it should be reopened to further investigate. Thanks!
