### ISSUE TITLE
Website Appearance: Automatic broken on macOS

### ISSUE THREAD

**Issue by jannis-baum** [zen-browser/desktop#9151]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

The Website Appearance set to Automatic defaults to dark mode, and doesn't inherit from system settings on macOS.

This is a reopen of #6708 because that issue was incorrectly closed by @zen-browser-auto during "repo cleanup" within one week of it being opened. Since the bug still exists (can reproduce in Troubleshoot Mode, cannot reproduce on Firefox) I am reopening as suggested.

### Expected behavior

"Website Appearance: Automatic" dynamically adapts to system appearance setting

### Actual behavior

"Website Appearance: Automatic" always sets Zen to dark mode, even after restarting with system light mode

### Steps to reproduce

- set "Website Appearance: Automatic" on macOS
- toggle system light/dark mode and see that nothing happens

### Version

1.13.2b (Firefox 139.0.4) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Settings

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Could you please send a video?

**Comment by jannis-baum** [comment]
> Could you please send a video?

Sorry, completely missed this. Just recorded the video in troubleshoot mode, then when I restarted Zen it was upgraded to 1.14b and the issue was fixed haha. Here is the video on 1.13.2b just for reference:

https://github.com/user-attachments/assets/f1198f7e-fb12-42f9-b4b2-35fbc6843551

Anyways, I'll close this since it seems to have been fixed. Thanks!

**Comment by ChucKN0risK** [comment]
@jannis-baum You don't have this issue anymore? Because I still do on macOS Sonoma 14.5.

**Comment by jannis-baum** [comment]
@ChucKN0risK I'm on Sequoia 15.6.1 and Zen 1.15.5b and it works for me

**Comment by Reupenny** [comment]
I have the same issue but mine is stuck in light mode when its on auto.
I was having this issue on Sequoia, now on Tahoe and I still have the issue. 
Zen 1.16.2b
